### PR TITLE
makepkg-mingw.conf: add RUSTFLAGS

### PR DESCRIPTION
**Pull request by ognevny**
frame-pointers are already enabled for rust package, so let's put it for all rust-based packages

push repo checksum while at it

### CODE REVIEW

**Comment by Biswa96** [comment]
Did you try to compile and use any rust packages with this change?

**Comment by ognevny** [comment]
> Did you try to compile and use any rust packages with this change?

rust compiler works, you mean _other_ programs? I can test Zed

**Comment by Biswa96** [comment]
I meant other programs, just normal use cases.

**Comment by ognevny** [comment]
Zed works

**Comment by lazka** [comment]
Arch does it too, so fine I guess: https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/4950709a4fd95172c6ffa04abd78b0fce8ff4591/rust.conf

**Comment by ognevny** [comment]
> Arch does it too, so fine I guess: https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/4950709a4fd95172c6ffa04abd78b0fce8ff4591/rust.conf

Zed is built with this flag for more than a week, and for now the only new issues about are known (not related to such change)

**Pull request merged**
