### PR TITLE
Remove autotools from base-devel

### PR DESCRIPTION
**Pull request by lazka**
All packages depend on it explicitly now.

### CODE REVIEW

**Comment by Biswa96** [comment]
Will base-devel be removed? Every script which depends on base-devel has to change to autotools?

**Comment by lazka** [comment]
> Will base-devel be removed?

No, I'm just cleaning it up.

> Every script which depends on base-devel has to change to autotools?

At least in our repo that's already the case.

**Comment by Biswa96** [comment]
CI has this error in clang while building vala:

```
/usr/bin/m4: internal error detected; please report this bug to <bug-m4@gnu.org>: Segmentation fault
```

**Comment by lazka** [comment]
reverted the m4 rebuild for now

**Pull request merged**
