### PR TITLE
[RFC] Add a separate pacman-contrib package

### PR DESCRIPTION
**Pull request by lazka**
* Split pacman-contrib out
* Add it to base

If we do this existing users will lose the pacman-contrib scripts on update. The solution would be to tell them to `pacman -Sy base`

This fixes the problem that pacman-contrib links against the system libalpm when build with pacman in one go.

### CODE REVIEW

**Comment by elieux** [comment]
What is in pacman-contrib anyway? Can you post a file listing?

**Comment by lazka** [comment]
```
$ tree pkg/pacman-contrib/
pkg/pacman-contrib/
└── usr
    ├── bin
    │   ├── checkupdates
    │   ├── paccache
    │   ├── pacdiff
    │   ├── paclist
    │   ├── paclog-pkglist
    │   ├── pacscripts
    │   ├── pacsearch
    │   ├── pacsort.exe
    │   ├── pactree.exe
    │   ├── rankmirrors
    │   └── updpkgsums
    ├── lib
    │   └── systemd
    │       └── system
    │           ├── paccache.service
    │           └── paccache.timer
    └── share
        ├── man
        │   └── man8
        │       ├── checkupdates.8.gz
        │       ├── paccache.8.gz
        │       ├── pacdiff.8.gz
        │       ├── pacsort.8.gz
        │       ├── pactree.8.gz
        │       └── updpkgsums.8.gz
        └── vim
            └── vimfiles
                ├── ftdetect
                │   └── PKGBUILD.vim
                ├── ftplugin
                │   └── PKGBUILD.vim
                └── syntax
                    └── PKGBUILD.vim

13 directories, 22 files
```

**Comment by elieux** [comment]
Thanks. I wanted to confirm it needs to stay in base. Given `updpkgsums` is there, I have no objections at this time.

**Comment by lazka** [comment]
Thanks. For some more context: pacman-contrib was part of pacman itself until 5.1.0 where it was split out.

**Pull request merged**
