### PR TITLE
spdlog: add

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by Biswa96** [comment]
Why? We want to keep less packages in msys2 as we focus on mingw packages.

**Comment by neheb** [comment]
Porting a Linux package to Windows. MinGW seems too hard (lots of POSIX APIs used).

**Comment by Biswa96** [comment]
spdlog is already available in mingw packages https://packages.msys2.org/base/mingw-w64-spdlog

**Comment by lazka** [comment]
We only add packages here that we need for building mingw ones.

**Comment by neheb** [comment]
OK

**Pull request closed without merging**
