### PR TITLE
reflex: Update to 20200715

### PR DESCRIPTION
**Pull request by jannick0**
* reflex/PKGBUILD:
  - update version to 20200715
  - change to github releases whose unzipped packages have a different
    folder name.
  - add variables _src_dir and _build_dir for better maintenance.

### CODE REVIEW

**Comment by Biswa96** [comment]
Why is the actual source URL removed? It seems that the GitHub repository itself imports the code from invisible-island.net.

**Comment by jannick0** [comment]
Correct - plus the benefit to immediately see the changes between releases on github.  (I will apply the same to the next update of btyacc, too.)

**Comment by Biswa96** [comment]
At least, make the old source link as a comment instead of deleting it. See other PKGBUILD files.

**Comment by jannick0** [comment]
Your politeness is demanding ... done.

**Comment by lazka** [comment]
Not a big fan of the builddir changes, but OK..

**Pull request merged**
