### PR TITLE
mintty: bump the default window size a bit

### PR DESCRIPTION
**Pull request by lazka**
80x24 is too small for me (and maybe others?) and it's not that obvious
that you can change the size in the settings, so maybe a larger default
helps new users.

### CODE REVIEW

**Comment by lazka** [comment]
image

**Comment by Biswa96** [comment]
Would it be same if the columns and rows options are provided from launcher instead of patching mintty?

**Comment by lazka** [comment]
> Would it be same if the columns and rows options are provided from launcher instead of patching mintty?

The the user wouldn't be able to change it in the mintty settings.

**Comment by Biswa96** [comment]
> Then the user wouldn't be able to change it in the mintty settings.

How about adding a config file with the those settings? Assuming it won't replace the current one.

**Comment by lazka** [comment]
I could add a /etc/minttyrc, but then any GUI changes will get written there instead of ~/.minttyrc, which means there will be a .pacnew file on every future mintty update.

I'm fine with both ways, but prefer the patch tbh.

**Comment by Biswa96** [comment]
OK, understood.

**Comment by 1480c1** [comment]
I personally use something like 120x30 using
```bash
Columns=120
Rows=30
```
in the .minttyrc file

**Comment by mintty** [comment]
80x24 is kind of a traditional standard terminal size.
My preference is 80x33 but I'd not make that a default.
Settings in $HOME are a proper place for personal preferences.
Anyway, mintty 3.7.3 will not save changes to /etc/minttyrc anymore.

**Pull request merged**
