### PR TITLE
perl-Scalar-List-Utils: update to 1.54

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
This compiles in my PC but not in CI !?

**Comment by Biswa96** [comment]
This compiles in my PC but not in CI !? Do we need `libcrypt-devel` as make depends?

**Comment by lazka** [comment]
> Do we need `libcrypt-devel` as make depends?

yes, please try that

**Comment by Biswa96** [comment]
Done.

**Pull request merged**
