### PR TITLE
Use zstd for all packages now

### PR DESCRIPTION
**Pull request by lazka**
It's been long enough and everyone should have a pacman that supports it

### CODE REVIEW

**Comment by Biswa96** [comment]
> everyone should have a pacman that supports it

Let's have a Twitter poll.

**Comment by lazka** [comment]
I think it was broken in the meantime anyway, since pacman depends on gnupg/curl and they use zst

**Comment by jeremyd2019** [comment]
> It's been long enough and everyone should have a pacman that supports it

Maybe not, #2300

**Comment by mati865** [comment]
Always there will be somebody trying to update from ancient version...

**Pull request merged**
