### PR TITLE
base: Remove unneeded Linux-specific packages and dependencies

### PR DESCRIPTION
**Pull request by elieux**

### CODE REVIEW

**Comment by lazka** [comment]
lgtm, the only thing I use regularly is pkgfile, but it can always be installed

**Comment by elieux** [comment]
> the only thing I use regularly is pkgfile

Is there something wrong with `pacman -F`?

**Comment by Alexpux** [comment]
pkgfile is small utility so I prefer to leave it in base

**Comment by elieux** [comment]
> pkgfile is small utility so I prefer to leave it in base

I must ask again, what's wrong with `pacman -F`?

**Comment by lazka** [comment]
> Is there something wrong with `pacman -F`?

TIL, never mind then XD

**Comment by elieux** [comment]
> TIL, never mind then XD

Pacman deveopers added that some years ago. It might be a bit slower than pkgfile, but being built in beats that IMO.

**Pull request merged**
