### PR TITLE
libxml2-python: Add Python 3 support

### PR DESCRIPTION
**Pull request by lazka**
Also build the Python 3 bindings and clean things up a bit.

### CODE REVIEW

**Comment by Alexpux** [comment]
@lazka I dont like this changes.

**Comment by lazka** [comment]
ok, anything in particular? The package splitting changes? That we build for Python 3?

**Comment by Alexpux** [comment]
@lazka to many line with rm :)

**Comment by lazka** [comment]
ok, fair enough.

**Comment by lazka** [comment]
I'll open a new PR when I find some time for this again.

**Pull request closed without merging**
