### PR TITLE
avr-binutils: New package

### PR DESCRIPTION
**Pull request by fauxpark**
Binutils targeting Atmel AVR microcontrollers.

### CODE REVIEW

**Comment by fauxpark** [comment]
@Alexpux is there anything holding this back? I plan to add avr-gcc and avr-libc next if this is merged.

**Comment by stahta01** [comment]
Should not this package be a mingw package?
Tim S.

**Comment by fauxpark** [comment]
Probably, but I wouldn't know how to make it one. Might be as simple as opening a MinGW terminal instead of MSYS.

**Comment by fauxpark** [comment]
Closing, will try to figure out how to get avr-gcc compiling at some point soon.

**Pull request closed without merging**
