### PR TITLE
libxml2: Fix dependencies (compile-time and run-time)

### PR DESCRIPTION
**Pull request by jannick0**
The post_install hook of the package calls 'xmlcatalog.exe' which is part
of the package.  This commit fixes run-time dependency errors which occur
upon installing and using the package.

* libxml2/PKGBUILD:
  - add required package dependencies, implied by make-dependencies
  - remove trailing white spaces

### CODE REVIEW

**Comment by Biswa96** [comment]
Don't we need to incrment pkgrel?

**Comment by Biswa96** [comment]
Don't we need to increment `pkgrel`?

**Comment by jannick0** [comment]
> Don't we need to increment `pkgrel`?

Absolutely. Thanks - will force-push shortly.

**Comment by lazka** [comment]
The dependencies are set in package_libxml2() so your change doesn't do anything. If a dependency is missing add it there.

**Comment by jannick0** [comment]
@lazka Just force-pushed new series of commits which pass all checks. They display changes in tiny steps which you could squash when merging into the repo if OK.  Otherwise I could squash them, too, in case you prefer. 

> The dependencies are set in package_libxml2() so your change doesn't do anything. If a dependency is missing add it there.

Here two issues which emerged after delving into this:
* for split packages the global `depends` array needs to be defined to be passed on to `makepkg`'s dependency checks (see reference in one of the commit messages)
* I removed indirect dependencies to `ncurses` and `ncurses-devel` from this package. BTW: There are far many more throughout the repo packages.  Do you intend to remove them for cleanup or are you happy as it is right now?  I am not sure how this impacts `pacman` which, however, identifies indirect dependencies by traversal of the dependency tree upon install/upgrade (as far as I can tell).

**Comment by lazka** [comment]
I've created #3364 for the second commit.

For (1): we already makedepend on the devel packages, so this doesn't add anything.
(3) this will delete the catalog file and anything other packages like docbook-xml will write in there. While I don't know if the current approach is good, this is definitely wrong.

**Pull request closed without merging**
