### PR TITLE
msys2-runtime: upgrade to Cygwin v3.3.2

### PR DESCRIPTION
**Pull request by dscho**
Patches plucked from https://github.com/msys2/msys2-runtime/pull/63.

### CODE REVIEW

**Comment by dscho** [comment]
I've tested this a bit, in particular the Ctrl+C handling, and it looks good to me.

**Comment by dscho** [comment]
@lazka could I ask you to review this PR and merge it at your leisure?

**Comment by piotrvv** [comment]
error: failed to commit transaction (conflicting files)
msys2-runtime: /usr/share/man/man1/mkpasswd.1.gz exists in filesystem (owned by expect)
Errors occurred, no packages were upgraded.

**Comment by dscho** [comment]
```
$ pacman -Qo /usr/share/man/man1/mkpasswd.1.gz
error: No package owns /usr/share/man/man1/mkpasswd.1.gz
```

**Comment by piotrvv** [comment]
As of version 3.2.0, this file does not exist. In version 3.3.2 it is. In path x86_64-pc-msys\winsup\doc

**Comment by jeremyd2019** [comment]
https://packages.msys2.org/package/expect?repo=msys&variant=x86_64

Expect does indeed provide `/usr/share/man/man1/mkpasswd.1.gz`.

**Comment by lazka** [comment]
<details>

```diff
--- a.txt	2021-11-10 20:51:33.094492700 +0100
+++ b.txt	2021-11-10 20:51:19.150466600 +0100
@@ -9,6 +9,7 @@
 usr/bin/gencat.exe
 usr/bin/getconf.exe
 usr/bin/getfacl.exe
+usr/bin/gmondump.exe
 usr/bin/kill.exe
 usr/bin/ldd.exe
 usr/bin/ldh.exe
@@ -22,6 +23,7 @@
 usr/bin/msys-2.0.dll
 usr/bin/passwd.exe
 usr/bin/pldd.exe
+usr/bin/profiler.exe
 usr/bin/ps.exe
 usr/bin/regtool.exe
 usr/bin/setfacl.exe
@@ -34,6 +36,10 @@
 usr/etc/defaults
 usr/etc/defaults/etc
 usr/etc/defaults/etc/cygserver.conf
+usr/etc/postinstall
+usr/etc/postinstall/cygwin-doc.sh
+usr/etc/preremove
+usr/etc/preremove/cygwin-doc.sh
 usr/libexec
 usr/libexec/getprocaddr32.exe
 usr/libexec/getprocaddr64.exe
@@ -47,9 +53,132 @@
 usr/share/doc/Msys/COPYING
 usr/share/doc/Msys/CYGWIN_LICENSE
 usr/share/doc/Msys/cygserver.README
+usr/share/doc/cygwin-api
+usr/share/doc/cygwin-api/compatibility.html
+usr/share/doc/cygwin-api/cygwin-api.html
+usr/share/doc/cygwin-api/cygwin-functions.html
+usr/share/doc/cygwin-api/docbook.css
+usr/share/doc/cygwin-api/func-cygwin-attach-handle-to-fd.html
+usr/share/doc/cygwin-api/func-cygwin-conv-path-list.html
+usr/share/doc/cygwin-api/func-cygwin-conv-path.html
+usr/share/doc/cygwin-api/func-cygwin-create-path.html
+usr/share/doc/cygwin-api/func-cygwin-internal.html
+usr/share/doc/cygwin-api/func-cygwin-login.html
+usr/share/doc/cygwin-api/func-cygwin-logon_user.html
+usr/share/doc/cygwin-api/func-cygwin-misc.html
+usr/share/doc/cygwin-api/func-cygwin-posix-path-list-p.html
+usr/share/doc/cygwin-api/func-cygwin-set-impersonation-token.html
+usr/share/doc/cygwin-api/func-cygwin-split-path.html
+usr/share/doc/cygwin-api/func-cygwin-stackdump.html
+usr/share/doc/cygwin-api/index.html
+usr/share/doc/cygwin-api/std-bsd.html
+usr/share/doc/cygwin-api/std-deprec.html
+usr/share/doc/cygwin-api/std-gnu.html
+usr/share/doc/cygwin-api/std-notes.html
+usr/share/doc/cygwin-api/std-notimpl.html
+usr/share/doc/cygwin-api/std-solaris.html
+usr/share/doc/cygwin-ug-net
+usr/share/doc/cygwin-ug-net/are-free.html
+usr/share/doc/cygwin-ug-net/brief-history.html
+usr/share/doc/cygwin-ug-net/chattr.html
+usr/share/doc/cygwin-ug-net/cygcheck.html
+usr/share/doc/cygwin-ug-net/cygpath.html
+usr/share/doc/cygwin-ug-net/cygwin-ug-net.html
+usr/share/doc/cygwin-ug-net/dll.html
+usr/share/doc/cygwin-ug-net/docbook.css
+usr/share/doc/cygwin-ug-net/dumper.html
+usr/share/doc/cygwin-ug-net/gdb.html
+usr/share/doc/cygwin-ug-net/getconf.html
+usr/share/doc/cygwin-ug-net/getfacl.html
+usr/share/doc/cygwin-ug-net/gmondump.html
+usr/share/doc/cygwin-ug-net/gprof.html
+usr/share/doc/cygwin-ug-net/highlights.html
+usr/share/doc/cygwin-ug-net/index.html
+usr/share/doc/cygwin-ug-net/kill.html
+usr/share/doc/cygwin-ug-net/ldd.html
+usr/share/doc/cygwin-ug-net/locale.html
+usr/share/doc/cygwin-ug-net/lsattr.html
+usr/share/doc/cygwin-ug-net/minidumper.html
+usr/share/doc/cygwin-ug-net/mkgroup.html
+usr/share/doc/cygwin-ug-net/mkpasswd.html
+usr/share/doc/cygwin-ug-net/mount.html
+usr/share/doc/cygwin-ug-net/ntsec.html
+usr/share/doc/cygwin-ug-net/ov-ex-unix.html
+usr/share/doc/cygwin-ug-net/ov-ex-win.html
+usr/share/doc/cygwin-ug-net/ov-new.html
+usr/share/doc/cygwin-ug-net/overview.html
+usr/share/doc/cygwin-ug-net/passwd.html
+usr/share/doc/cygwin-ug-net/pldd.html
+usr/share/doc/cygwin-ug-net/proc.html
+usr/share/doc/cygwin-ug-net/profiler.html
+usr/share/doc/cygwin-ug-net/programming.html
+usr/share/doc/cygwin-ug-net/ps.html
+usr/share/doc/cygwin-ug-net/regtool.html
+usr/share/doc/cygwin-ug-net/setfacl.html
+usr/share/doc/cygwin-ug-net/setmetamode.html
+usr/share/doc/cygwin-ug-net/setup-env.html
+usr/share/doc/cygwin-ug-net/setup-files.html
+usr/share/doc/cygwin-ug-net/setup-locale.html
+usr/share/doc/cygwin-ug-net/setup-maxmem.html
+usr/share/doc/cygwin-ug-net/setup-net.html
+usr/share/doc/cygwin-ug-net/ssp.html
+usr/share/doc/cygwin-ug-net/strace.html
+usr/share/doc/cygwin-ug-net/tzset.html
+usr/share/doc/cygwin-ug-net/umount.html
+usr/share/doc/cygwin-ug-net/using-cygserver.html
+usr/share/doc/cygwin-ug-net/using-cygwinenv.html
+usr/share/doc/cygwin-ug-net/using-effectively.html
+usr/share/doc/cygwin-ug-net/using-filemodes.html
+usr/share/doc/cygwin-ug-net/using-specialnames.html
+usr/share/doc/cygwin-ug-net/using-textbinary.html
+usr/share/doc/cygwin-ug-net/using-utils.html
+usr/share/doc/cygwin-ug-net/using.html
+usr/share/doc/cygwin-ug-net/windres.html
 usr/share/man
+usr/share/man/man1
+usr/share/man/man1/chattr.1
+usr/share/man/man1/cygcheck.1
+usr/share/man/man1/cygpath.1
+usr/share/man/man1/cygwin.1
+usr/share/man/man1/dumper.1
+usr/share/man/man1/getconf.1
+usr/share/man/man1/getfacl.1
+usr/share/man/man1/gmondump.1
+usr/share/man/man1/intro.1
+usr/share/man/man1/kill.1
+usr/share/man/man1/ldd.1
+usr/share/man/man1/locale.1
+usr/share/man/man1/lsattr.1
+usr/share/man/man1/minidumper.1
+usr/share/man/man1/mkgroup.1
+usr/share/man/man1/mkpasswd.1
+usr/share/man/man1/mount.1
+usr/share/man/man1/passwd.1
+usr/share/man/man1/pldd.1
+usr/share/man/man1/profiler.1
+usr/share/man/man1/ps.1
+usr/share/man/man1/regtool.1
+usr/share/man/man1/setfacl.1
+usr/share/man/man1/setmetamode.1
+usr/share/man/man1/ssp.1
+usr/share/man/man1/strace.1
+usr/share/man/man1/tzset.1
+usr/share/man/man1/umount.1
 usr/share/man/man3
+usr/share/man/man3/cygwin_attach_handle_to_fd.3
+usr/share/man/man3/cygwin_conv_path.3
+usr/share/man/man3/cygwin_conv_path_list.3
+usr/share/man/man3/cygwin_create_path.3
+usr/share/man/man3/cygwin_internal.3
+usr/share/man/man3/cygwin_logon_user.3
+usr/share/man/man3/cygwin_posix_path_list_p.3
+usr/share/man/man3/cygwin_set_impersonation_token.3
+usr/share/man/man3/cygwin_split_path.3
+usr/share/man/man3/cygwin_stackdump.3
+usr/share/man/man3/intro.3
 usr/share/man/man3/regex.3
+usr/share/man/man5
+usr/share/man/man5/proc.5
 usr/share/man/man7
 usr/share/man/man7/regex.7
 usr/x86_64-pc-msys
@@ -242,6 +371,7 @@
 usr/x86_64-pc-msys/include/sys/_tz_structs.h
 usr/x86_64-pc-msys/include/sys/acl.h
 usr/x86_64-pc-msys/include/sys/cdefs.h
+usr/x86_64-pc-msys/include/sys/clipboard.h
 usr/x86_64-pc-msys/include/sys/config.h
 usr/x86_64-pc-msys/include/sys/cpuset.h
 usr/x86_64-pc-msys/include/sys/custom_file.h
```

</detail>

**Comment by lazka** [comment]
I don't think we can conflict with a none-core package here, because there is no way to update it before msys2-runtime, so we either have to remove the file for now, or use "!zipman".

**Comment by lazka** [comment]
> Expect does indeed provide `/usr/share/man/man1/mkpasswd.1.gz` (which is odd because it doesn't seem to provide a `mkpasswd` command).

The Arch Linux variant does: https://archlinux.org/packages/extra/x86_64/expect/

**Comment by lazka** [comment]
Since I'm not allowed to push here, I added this to master after merging: b3c1faddabb

**Comment by lazka** [comment]
There are some regression fixes lined up in cygwin-patches, so I'll keep this in staging for a bit...

**Comment by dscho** [comment]
> Since I'm not allowed to push here

Oh no, what did I do wrong? I thought the default is to let maintainers push...

> I added this to master after merging: [b3c1fad](https://github.com/msys2/MSYS2-packages/commit/b3c1faddabba74aded26f2cc4c47b7d810a3e722)

Thank you!

We should probably revisit (read: revert) this in, say, 6 months from now.

> There are some regression fixes lined up in cygwin-patches, so I'll keep this in staging for a bit...

Sounds good! Would you have a link for me so I can monitor for regressions?

**Comment by lazka** [comment]
> > Since I'm not allowed to push here
> 
> Oh no, what did I do wrong? I thought the default is to let maintainers push...

not sure. I know it's off for orga forks, but that's not the case here. maybe I missed something.

> > I added this to master after merging: [b3c1fad](https://github.com/msys2/MSYS2-packages/commit/b3c1faddabba74aded26f2cc4c47b7d810a3e722)
> 
> Thank you!
> 
> We should probably revisit (read: revert) this in, say, 6 months from now.
> 
> > There are some regression fixes lined up in cygwin-patches, so I'll keep this in staging for a bit...
> 
> Sounds good! Would you have a link for me so I can monitor for regressions?

https://cygwin.com/pipermail/cygwin-patches/2021q4/thread.html

the last two pipe related patches, one is already pushed

**Comment by dscho** [comment]
Oh right, I saw those.

Do we have a regression test suite we can run to test the MSYS2 runtime?

**Comment by lazka** [comment]
> Do we have a regression test suite we can run to test the MSYS2 runtime?

No :(

**Comment by dscho** [comment]
I asked about using `winsup/testsuite/` in the `#cygwin-developers` channel on Libera today, and it seems that the situation isn't really favorable... Then I tried to simply clone https://git.savannah.gnu.org/git/dejagnu next to the `msys2-runtime` checkout and then run `make check`, but did not come far, being faced with an immediate compile failure. :-(

**Pull request merged**
