### PR TITLE
fmt: new C++ formatting library, v6.1.1

### PR DESCRIPTION
**Pull request by bbolli**
This library might also help the MSYS2 users.

### CODE REVIEW

**Comment by lazka** [comment]
Since upstream supports Windows I wonder if this should built with mingw instead.

**Comment by bbolli** [comment]
This is already part of the MINGW-packages repo.

**Comment by lazka** [comment]
Ah, right, never mind then.

**Comment by bbolli** [comment]
Obviously no interest to add this.

**Comment by lazka** [comment]
We try keep the cygwin parts small and focus on native packages, sorry :/

**Comment by bbolli** [comment]
No problem; I assumed as much :-)

**Pull request closed without merging**
