### PR TITLE
msys2-runtime: do not fall back to ExitProcess() on Ctrl+C

### PR DESCRIPTION
**Pull request by dscho**
This corresponds to https://github.com/msys2/msys2-runtime/pull/50.

### CODE REVIEW

**Comment by naveen521kk** [comment]
bump pkgrel

**Comment by dscho** [comment]
> 
> 
> bump pkgrel

Thanks for paying attention ;-)

**Comment by naveen521kk** [comment]
Thanks for the PR :).

**Comment by dscho** [comment]
Oh nice, you can merge MSYS2-packages PRs now!

**Pull request merged**
