### PR TITLE
git: update to 3.36.0 & rebase patches & use CYGWIN_CHOST

### PR DESCRIPTION
**Pull request by 1480c1**
git.exe was missing the msys-z.dll and msys-iconv-2.dll dep and was thus failing to run in an isolated setting

```bash
ldd /usr/bin/git.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff9372e0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff936ef0000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff934ae0000)
        msys-iconv-2.dll => /usr/bin/msys-iconv-2.dll (0x5603f0000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
        msys-intl-8.dll => /usr/bin/msys-intl-8.dll (0x430b30000)
        msys-z.dll => /usr/bin/msys-z.dll (0x522fe0000)
        msys-pcre2-8-0.dll => /usr/bin/msys-pcre2-8-0.dll (0x25d1c20000)
```

### CODE REVIEW

**Comment by Biswa96** [comment]
Isolated settings? 🤔

**Comment by 1480c1** [comment]
> Isolated settings? 🤔

In an archlinux container with the pacman-mirror package and the repo's added to pacman.conf and running pacman while explicity prefixing them with mingw64/ or msys/. For the msys/ packages, I first have to download with -Sw and then
```bash
pacman -Sup \
    msys/git \
    ... \
    | sed 's#file://##' \
    | xargs -n1 tar xf
```

**Comment by 1480c1** [comment]
Seems there might be more because of the /usr/lib/git-core/*.exe. marking this as draft until I have time to go through all of them

**Comment by 1480c1** [comment]
limiting this PR to just updating git and the patches, found a way to pull in all deps using pactree if using pacman -Sw

**Comment by lazka** [comment]
thanks.

**Comment by lazka** [comment]
(in general, more explicit dependencies are always welcome)

**Pull request merged**
