### PR TITLE
tmux: fix startup in local session

### PR DESCRIPTION
**Pull request by rkitover**
Add a patch to fix tmux failing to start in a local terminal session when using Microsoft Terminal and other Windows terminals.

See:

https://github.com/microsoft/terminal/issues/5132

### CODE REVIEW

**Comment by jeremyd2019** [comment]
It looks like there have been some fixes to cygwin for tmux since the last release (eg https://github.com/cygwin/cygwin/commit/186ee9b67607deeb19993385bc2c07ba20050237).  Perhaps they will make this patch unnecessary, once they make a new release.

**Comment by rkitover** [comment]
Not possible, tmux has the client send the terminal file descriptor over the client <-> server UNIX domain socket, which is possible on UNIX, but not possible on Cygwin because it emulates UNIX sockets using a localhost TCP socket.

**Comment by jeremyd2019** [comment]
OK I guess I just don't understand then.  I thought that tmux mostly worked, except when run from a Windows console (as opposed to a Cygwin pty from the likes of mintty), and that recent fixes to cygwin would help in that scenario.  However, I do know that Cygwin does not support passing file descriptors over unix-domain sockets

**Comment by rkitover** [comment]
I will explain.

See [here](https://github.com/tmux/tmux/blob/master/server-client.c#L3043) in the upstream sources.

What this does, is set the server client handler terminal file descriptor to the client terminal device path, since the code above that to receive the terminal file descriptor from the client does nothing.

In mintty or ssh, the client uses a Cygwin pty device, so it is possible for the server process to access it directly.

In a local native Windows terminal session, such as in Microsoft Terminal, the client terminal device is a special file that is not accessible from another process, such as the tmux server process, by any means. Windows does not allow that.

This patch is very simple (it was however, a lot of research and work for me to make.) What it does is set up a pty device for the server client handler, and pass data between it and the actual client terminal on the socket using libevent handlers.

**Comment by jeremyd2019** [comment]
> In a local native Windows terminal session, such as in Microsoft Terminal, the client terminal device is a special file that is not accessible from another process, such as the tmux server process, by any means. Windows does not allow that.

It seemed like @tyan0 had something in place now in Cygwin to allow that.

**Comment by rkitover** [comment]
> It seemed like @tyan0 had something in place now in Cygwin to allow that.

Do you have any more details? Even if that was the case, tmux would still have to be patched for this, as you can see from my explanation above.

And why would this be better than my solution? I think it's clean and simple. I have a PR pending in tmux upstream for it.

**Comment by tyan0** [comment]
At least for cygwin, tmux works on cygwin 3.5.0, 3.5.1 and 3.5.4 (which will be released soon) in windows terminal. This is because https://github.com/cygwin/cygwin/commit/3721a756b0d8067cf070e2aedcf3ea5e32e47270 makes the console accessible from other terminals like ptys.

Unfortunately, 3.5.3 has a regression due to the commit https://github.com/cygwin/cygwin/commit/cf121e088f928c68a8e3c799db97478c89b6dd96 which prevents tmux from starting in a console. This is already fixed by https://github.com/cygwin/cygwin/commit/186ee9b67607deeb19993385bc2c07ba20050237, so tmux will work again in 3.5.4.

I am not sure what problem this PR fixes, but could you please check if tmux works on 3.5.1 with your scenario?

**Comment by tyan0** [comment]
msys2-runtime 3.5.1 can be downloaded from:
https://repo.msys2.org/msys/x86_64/msys2-runtime-3.5-3.5.1-2-x86_64.pkg.tar.zst
https://repo.msys2.org/msys/x86_64/msys2-runtime-3.5-devel-3.5.1-2-x86_64.pkg.tar.zst

and can be installed by:
```pacman -U msys2-runtime-3.5-3.5.1-2-x86_64.pkg.tar.zst msys2-runtime-3.5-devel-3.5.1-2-x86_64.pkg.tar.zst```

**Comment by rkitover** [comment]
@tyan0 question for you, is this new terminal device visible outside of the Cygwin virtual filesystem, like in the scenario where you have a `tmux.exe` bundled with the Cygwin dll and other dependent dlls.

**Comment by tyan0** [comment]
Is your question whether the console device is accessible from another installation of cygwin? If so, the answer is no.

**Comment by rkitover** [comment]
Not exactly.

My question is whether the console device is accessible **WITHOUT** an installation of Cygwin.

You may be aware of some Windows software that are not full native ports and use an msys or cygwin dll for a part of their functionality, sshfs for Windows is one such example. This software typically bundles the msys/cygwin dll in the same directory as the exetuable with any other dependent dlls.

In this scenario, there is no full virtual filesystem, like when running a program from an msys/cygwin installation.

My question is whether the console device is accessible in this scenario, because I am working on a "more" native package for tmux made in this way.

**Comment by tyan0** [comment]
Yes. The console devices (/dev/cons*) and their functionalities are provided by cygwin1.dll (msys-2.0.dll), so the program loading cygwin1.dll (msys-2.0.dll) can access to other consoles if exist (i.e. some program using that dll has been opened in the console device, such as Windows Terminal, cmd.exe).

**Comment by rkitover** [comment]
Don't know what happened here or if this is the actual patch that I sent, anyway I'm closing this.

@tyan0 thank you for your work on the Cygwin runtime for this and thank you for explaining how this works to me.

**Pull request closed without merging**
