### PR TITLE
pacman-mirrors: add BFSU

### PR DESCRIPTION
**Pull request by alissa-tung**

### CODE REVIEW

**Comment by lazka** [comment]
is there rsync support?

**Comment by alissa-tung** [comment]
Sorry I am not sure. https://mirrors.bfsu.edu.cn/status/
Other mirrors are rsyncing, if BFSU MSYS2 is not maybe a issue can be filed

**Comment by lazka** [comment]
We prefer mirrors which provide rsync access so we can monitor them. All others go to tier 2.

I've created #2775. I'll take it from here, so closing this for now.

Thanks!

**Comment by alissa-tung** [comment]
That's reasonable. (BTW, I filed this MR because BFSU mirror is a mirror of Tuna mirror which is sometime faster and more stable). Maybe I gonna connect Tuna for help if I can.

**Comment by lazka** [comment]
Turns out rsync is supported (I somehow did something wrong when testing for it I guess), so this is fine as is.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
