### PR TITLE
msys2-runtime-3.3: add -Wno-error for additional warning on i686 build

### PR DESCRIPTION
**Pull request by jeremyd2019**
On i686, an additional warning showed up that failed the build.  This adds this warning to the CFLAGS/CXXFLAGS exclusions.

```
/t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc: In function 'off_t format_proc_swaps(void*, char*&)': /t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc:1964:43: error: '%s' directive writing 4 bytes into a region of size between 1 and 2147483606 [-Werror=format-overflow=]
 1964 |           bufptr += sprintf (bufptr, "%s%s%s\t\t%llu%s\t%llu%s\t%d\n",
      |                                           ^~
......
 1967 |                                         "file",
      |                                         ~~~~~~
/t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc:1964:38: note: directive argument in the range [0, 18014398501093376]
 1964 |           bufptr += sprintf (bufptr, "%s%s%s\t\t%llu%s\t%llu%s\t%d\n",
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc:1964:38: note: directive argument in the range [0, 18014398501093376]
/t/r/msys2-runtime-3.3/src/msys2-runtime/winsup/cygwin/fhandler_proc.cc:1964:29: note: 'sprintf' output between 54 and 2147483693 bytes into a destination of size 2147483647
 1964 |           bufptr += sprintf (bufptr, "%s%s%s\t\t%llu%s\t%llu%s\t%d\n",
      |                     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1965 |                                     filename,
      |                                     ~~~~~~~~~
 1966 |                                     tabo < 5 ? "\t\t\t\t\t" + tabo : " ",
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1967 |                                         "file",
      |                                         ~~~~~~~
 1968 |                                             total >> 10,
      |                                             ~~~~~~~~~~~~
 1969 |                                             total < 10000000000 ? "\t" : "",
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1970 |                                                 used  >> 10,
      |                                                 ~~~~~~~~~~~~
 1971 |                                                 used  < 10000000000 ? "\t" : "",
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1972 |                                                                 0);
      |                                                                 ~~
```

### CODE REVIEW

**Comment by jeremyd2019** [comment]
Even with this, the resulting package seems to be broken on i686.  Might have some debugging to do...

**Comment by jeremyd2019** [comment]
@dscho did you happen to run into issues building an updated msys2-runtime-3.3 for i686?

**Comment by jeremyd2019** [comment]
I don't know why this would make any sense:
```
Starting program: C:\msys32\usr\bin\bash.exe -l
[New Thread 4912.0x1398]
[New Thread 4912.0x1504]
[New Thread 4912.0x34d0]
warning: cYgFFFFFFFF 6122D4D8 0

Thread 1 received signal SIGSEGV, Segmentation fault.
memset () at ../../../../.././newlib/libc/machine/i386/memset.S:94
```

```
(gdb) bt
#0  memset () at ../../../../.././newlib/libc/machine/i386/memset.S:94
#1  0x61005eec in cygheap_init()@0 ()
    at ../../.././winsup/cygwin/cygheap.cc:258
#2  0x00000000 in ?? ()
(gdb) down
#1  0x61005eec in cygheap_init()@0 ()
    at ../../.././winsup/cygwin/cygheap.cc:258
258           cygheap = (init_cygheap *) memset (_cygheap_start, 0,
(gdb) down
#0  memset () at ../../../../.././newlib/libc/machine/i386/memset.S:94
94              rep
(gdb) p _cygheap_start
$2 = 0x612eb408 ""
(gdb) i regis
eax            0x0                 0
ecx            0x1f44              8004
edx            0x0                 0
ebx            0x61005eec          1627414252
esp            0x85c45c            0x85c45c
ebp            0x85f6dc            0x85f6dc
esi            0xffffffff          -1
edi            0x85d95c            8771932
eip            0x0                 0x0
eflags         0x10246             [ PF ZF IF RF ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x53                83
gs             0x2b                43
```
```
   0x61005ed0 <+112>:   movl   $0x7d10,0x8(%esp)
   0x61005ed8 <+120>:   movl   $0x0,0x4(%esp)
   0x61005ee0 <+128>:   movl   $0x612eb408,(%esp)
   0x61005ee7 <+135>:   call   0x61192d30 <memset>
```

So memset is screwed up somehow?!?

**Comment by jeremyd2019** [comment]
No, I stepped through it and it's trying to write to 0x612eb408 and getting a SIGSEGV there.  So maybe the linker stuff is messed up and it isn't turning out to be a writable section?

**Comment by jeremyd2019** [comment]
I downgraded gcc to the version that was in place the last time I built a working msys2-runtime-3.3 (11.3.0-4), and the problem persisted.  I then upgraded gcc back to the most recent, and downgraded binutils to the last known working (2.40-1) and the problem went away.  Next step will be to find the most recent binutils that still worked

**Comment by jeremyd2019** [comment]
2.40-1 was the last version that worked.

**Comment by dscho** [comment]
> @dscho did you happen to run into issues building an updated msys2-runtime-3.3 for i686?

Not recently, but keep in mind that Git for Windows i686 MSYS builds are essentially "stuck" with the toolchain version that is able to build the MSYS2 runtime v3.3 without any additional `-W` flags.

**Comment by lazka** [comment]
msys2-runtime-3.3 seems to be broken for me too (64bit), so maybe it's a 3.3+binutils problem?

**Comment by jeremyd2019** [comment]
> msys2-runtime-3.3 seems to be broken for me too (64bit), so maybe it's a 3.3 related problem?

"good", in that I don't have to try to track down a 32-bit specific issue :grin:

**Comment by jeremyd2019** [comment]
Did the previous revision of msys2-runtime-3.3 still work on 64-bit?  Seems like it would have, because I was actively using it on 32-bit... If so, maybe the update should be reverted if it is broken?

**Comment by jeremyd2019** [comment]
Yes, on x86_64 msys2-runtime-3.3-3.3.6-6 worked while -7 did not.

**Comment by lazka** [comment]
I'll revert later

**Comment by lazka** [comment]
I've reverted the package in the repo, and reverted the pkgrel bump (only).

If all fails, and this really is binutils specific, we can introduce a separate 2.40 binutils package.

**Comment by jeremyd2019** [comment]
Apparently not too important, I think I was the only one who reported an issue, and then on i686 simply because this is the only runtime version packaged that still builds there.  I assume you only checked on x86_64 because of my report, rather than some actual user of msys2-runtime-3.3 on x86_64 reporting an issue.

**Comment by lazka** [comment]
It was actually motivated by the upcoming msys2-runtime-3.4 for win7 users, and I wanted to check how things work with 3.3 for a comparison.

**Comment by jeremyd2019** [comment]
I've opened msys2/msys2-runtime#203.  This PR currently contains the patches from that, for testing purposes.  Once that is merged, I'll update this PR with the properly formatted patches (I just used `git format-patch` and manually moved them in for now, but should use the update-patches.sh script)

**Comment by lazka** [comment]
I can confirm that things start again with this.

I also noticed though that things like python3 fail to start due to missing symbols, like __cpuset_free, __cpuset_alloc.
Maybe backporting https://github.com/cygwin/cygwin/commit/d27e9fb29a92fc5984de51470d68d859783ab986 would help?

**Comment by jeremyd2019** [comment]
I was a little confused, that commit only showed as being in the 3.5 release.  Turns out it was already backported to 3.4 in msys2/msys2-runtime@797d1bbd2e115872df10cf1c15ccc6cfc99648d6.  Maybe I'm overthinking it (since it was already backported to a 3.4 point release) but maybe we could just backport the exported functions and leave the headers alone for 3.3?  (or at least mostly alone, might need to prototype the exported functions).

**Comment by lazka** [comment]
The motivation stated in the commit is coreutils, which we still haven't updated (it's on my todo list..), so I'd guess backporting it as a whole might help there in the future(?)

**Comment by jeremyd2019** [comment]
The commit was part of a whole series of commits tweaking cpuset.h, and appeared to start with making it compile with clang.  I'm kind of guessing here, that the version in 3.3 would probably work with coreutils, just not with clang (but we already know the clang we have in MSYS2-packages is not to be trusted to compile for the cygwin/msys2 target anyway).

In any event, this seems like something for a future PR against msys2-runtime and we can test some different things out.

**Pull request merged**
