### PR TITLE
gnupg: Switch the default keyserver to keyserver.ubuntu.com

### PR DESCRIPTION
**Pull request by lazka**
pool.sks-keyservers.net no longer exists, which makes pacman-key fail etc.

Patches are taken from https://salsa.debian.org/debian/gnupg2/-/tree/debian/main/debian/patches

Related Arch discussion: https://bugs.archlinux.org/task/71078

### CODE REVIEW

**Comment by lazka** [comment]
Before:

```
$ pacman-key --refresh
gpg: error retrieving 'alexey.pawlow@gmail.com' via WKD: No data
gpg: error reading key: No data
gpg: refreshing 1 key from hkps://hkps.pool.sks-keyservers.net
gpg: keyserver refresh failed: No name
==> ERROR: Could not update key: F40D263ECA25678A
...
```

After:

```
$ pacman-key --refresh
gpg: error retrieving 'alexey.pawlow@gmail.com' via WKD: No data
gpg: error reading key: No data
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: key F40D263ECA25678A: "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
...
```

**Comment by lazka** [comment]
upstream changed it too now: https://dev.gnupg.org/rG47c4e3e00a7ef55f954c14b3c237496e54a853c1

We should probably backport that.

**Comment by jeremyd2019** [comment]
Should this also be done to mingw-w64?  Or wait for upstream 2.2.29?

**Comment by lazka** [comment]
2.2.29 should be out soon, so I think we can wait there.

**Comment by lazka** [comment]
PR with upstream backport in #2566

**Pull request merged**
