### PR TITLE
msys2-runtime: Fix leaked handles during "symlink" creation

### PR DESCRIPTION
**Pull request by cbrt64**
A simple fix for #2060.

### CODE REVIEW

**Comment by lazka** [comment]
@cbrt64 would that also work https://github.com/msys2/Cygwin/pull/9?

**Comment by cbrt64** [comment]
That's better of course, what was I thinking with all those gotos. Rebuilt and tested at my end, works as expected. Feel free to close this and push yours; I'm just here poking around for fun whenever I get free time. Also, thanks for informing me of the "upstream" home for runtime patches.

**Comment by cbrt64** [comment]
BTW, I got a notification email for this PR, saying the build job was cancelled after 72+ hours. Not knowing much about how CI works, I hope this doesn't represent a way to DOS/overload github's build machines with spurious pull requests.

**Comment by Biswa96** [comment]
The build step went fine in CI. As this patch creates a new msys2-runtime package, CI build process crash when it tries to install the new package.

**Comment by lazka** [comment]
> That's better of course, what was I thinking with all those gotos. Rebuilt and tested at my end, works as expected. Feel free to close this and push yours; I'm just here poking around for fun whenever I get free time. Also, thanks for informing me of the "upstream" home for runtime patches.

Thanks for providing the initial fix and testing! I've added a README in a1d708c81d013e4526 to make this more clear. And I've create a PR for this: #2095

**Pull request closed without merging**
