### PR TITLE
CI: fix dll dependency check

### LINKED ISSUE #4611: CI: dll check doesn't work
It seems every package has the dll check fail with:
```
find: missing argument to `-exec'
```

I believe this is due to this line
https://github.com/msys2/MSYS2-packages/blob/ec5ca31736cbe33c62230cf2f8141b93b9d2f22e/.ci/ci-build.sh#L68

and find's `-exec` option not running its argument in a shell.  I get the same error with:
```
find ... -exec "echo '{}:' && ldd '{}';"
```
but get correct behavior with, for instance:
```
find ... -exec dash -c "echo '{}:' && ldd '{}'" \;
```

Or, avoiding a shell,
```
find ... -exec echo '{}:' \;  -exec ldd '{}' \;
```

Generally, I'm not sure that #3917 actually worked as intended.

### PR DESCRIPTION
**Pull request by jeremyd2019**
The find expression was broken for a couple of reasons: it does not run in a subshell (so cannot use && like that), and it needs split arguments not one quoted argument.  Avoid having to call echo by using -printf argument.

Fixes #4611

### CODE REVIEW

**Comment by jeremyd2019** [comment]
I did a run to test this: https://github.com/jeremyd2019/MSYS2-packages/actions/runs/9195655593/job/25291960933#step:10:609

Interestingly, the dll check seems to happen while dependencies are uninstalled (they are removed by makepkg, but have not yet been reinstalled while installing the package).  This is probably a tougher problem to solve, though, because this check is done for the whole `pkg` directory tree, but split packages are now installed/uninstalled individually.  Perhaps the dll dependency check should be moved into the per-package loop (and then might use `pacman -Qlq "$pkgname"` instead of `find`).

Also, why does the file check pipe pacman output through sed to remove extraneous output instead of using the `-q` option?

**Comment by jeremyd2019** [comment]
> > Perhaps the dll dependency check should be moved into the per-package loop (and then might use `pacman -Qlq "$pkgname"` instead of `find`).
> 
> Sounds good, afaics this is also done that way in the MINGW repo already

Hmm, I thought the CI scripts were synchronized at some point.  must have diverged again since then

**Comment by Biswa96** [comment]
Moving the scripts to a common repository may help.

**Comment by lazka** [comment]
Should we sync it here or in a separate PR?

**Comment by jeremyd2019** [comment]
I was thinking about doing it here, but the few differences are mostly specific to MINGW-packages.  I will try moving the dll checks though.

**Comment by jeremyd2019** [comment]
Sorry, I had other things come up and I didn't finish testing this yesterday.  I think it's ready now.

**Comment by lazka** [comment]
It got stuck on my first try: https://github.com/msys2/MSYS2-packages/actions/runs/9222109999/attempts/1

maybe just unlucky, we'll see.

**Comment by lazka** [comment]
it also got stuck the second time

**Comment by jeremyd2019** [comment]
https://cygwin.com/pipermail/cygwin/2024-May/256002.html

> I think the fix for this would be to add -Wl,--disable-high-entropy-va to
> ldh_LDFLAGS, as was done for strace and cygcheck at least.

**Comment by jeremyd2019** [comment]
https://cygwin.com/pipermail/cygwin-patches/2024q2/012696.html

**Comment by jeremyd2019** [comment]
https://github.com/msys2/msys2-runtime/commit/10b921681108b333d17d8438a45afe6fbc1169dd (also backported to cygwin 3.5 branch)

**Comment by lazka** [comment]
Thanks, see https://github.com/msys2/MSYS2-packages/pull/4656

**Pull request merged**
