### PR TITLE
gdb: Update to 10.2

### LINKED ISSUE #2361: Msys2 version of gdb 9.2-3 not compatible with mingw-w64-x86_64-gcc 10.2.0-6
## Describe the issue

Breakpoints set using Msys2 gdb 9.2-3 don't work with programs compiled with mingw-w64-x86_64-gcc 10.2.0-6

## Steps to Reproduce the Problem

Glenn.Burkhardt@AI234087 MSYS ~
$ g++ -g t.cpp -o t

$ gdb ./t
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'libstdcxx'
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from ./t...
(gdb) b main
Breakpoint 1 at 0x14000154d: file t.cpp, line 6.
(gdb) l
1       #define __USE_MINGW_ANSI_STDIO 1
2       #include <stdio.h>
3
4       int main()
5       {
6           size_t z = 0;
7
8           printf("%zu\n", z);
9       }
(gdb) b 8
Breakpoint 2 at 0x140001555: file t.cpp, line 8.
(gdb) r
Starting program: /home/glenn.burkhardt/t [New Thread 42340.0xaee8]
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x140001548 Cannot insert breakpoint 2.
Cannot access memory at address 0x140001555

Command aborted.

## Additional Context: Operating System, Screenshots

- OS: [e.g. Windows 10 Pro version 1809 64bit]

### PR DESCRIPTION
**Pull request by orgads**
Fixes #2361

### CODE REVIEW

**Comment by orgads** [comment]
Not tested yet. Not sure what should be tested, except simple debugging session.

**Comment by Biswa96** [comment]
Maybe search for gdb in issues both here and in mingw. Try out those manual tests.

**Comment by orgads** [comment]
Basic tests look good. I didn't find many issues that are not build-related (and build is ok here). One issue that I found is solved by this upgrade.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
