### PR TITLE
Fix initial upgrade on Windows

### LINKED ISSUE #1298: pacman -Syu Does Nothing
Hi Everybody,

I am trying to install Netbeans C++ on a new machine and I've done this several times in the past without issue however when I attempt to do it today "pacman -Syu" or "pacman -Su" do absolutely nothing.  I have followed the instructions for installing MSYS2 (I've tried 32 and 64 bit versions) as specified on the following webpage (https://www.msys2.org/)  

What's the problem?

Wayne

### PR DESCRIPTION
**Pull request by darrencl**
Modified `pacman.conf`

* Uncomment wget
* Ignore update gnupg

Closes #1298

### CODE REVIEW

**Comment by darrencl** [comment]
I am installing MSYS2 in 2 of my Windows 10 machine with the latest version, i.e. `msys2-x86_64-20190524.exe` and still have the issue on initial upgrade, which I need to use workaround that mentioned in [here](https://github.com/msys2/MSYS2-packages/issues/1298#issuecomment-410077518). 

I think this worth having to easily get the initial setup working without frustration on having to browse and update the `pacman.conf` manually.

**Comment by Biswa96** [comment]
There is a new release of msys2 installer here https://github.com/msys2/msys2-installer/releases. Did you try that?

**Comment by darrencl** [comment]
@Biswa96 Ha! I haven't tried that. Did this update the `pacman.conf` though?

**Comment by lazka** [comment]
Please try the newer linked installer anyway.

**Comment by darrencl** [comment]
@lazka @Biswa96 Hey guys, just got a chance on trying the nightly build and it works just fine. I'll close this issue then.

Thanks!

**Comment by lazka** [comment]
Thanks for testing!

**Pull request closed without merging**
