### PR TITLE
kicad7.x-library: Add package folder

### PR DESCRIPTION
**Pull request by stahta01**
This package folder provides common data libraries for a MINGW kicad package I am working on. Currently trying to get UCRT64 kicad to run, before doing the MINGW package PR.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Is there a reason why this package will be called `kicad7.x-library` instead of (an unversioned) `kicad-library`?

**Comment by mmuetzel** [comment]
More general: I see your point in trying to reduce the installed data. But I don't know if the MSYS2 environment should be used as a data dump for the other (native) environments.

@lazka: What's your take on this?

**Comment by stahta01** [comment]
> Is there a reason why this package will be called `kicad7.x-library` instead of (an unversioned) `kicad-library`?

My long term plan is to allow 2 or 3 version of kicad packages at once.
And, to use the largest of each major version.
As if the kicad people release an kicad 7.1 kicad7.x-library becomes 7.1 instead of the current 7.0.

And, I plan to add an kicad6.x-library that will be 6.0 or maybe 6.1.

Tim S.

**Comment by stahta01** [comment]
> More general: I see your point in trying to reduce the installed data. But I don't know if the MSYS2 environment should be used as a data dump for the other (native) environments.
> 
> @lazka: What's your take on this?

I mostly agree; but, had no idea where else to put it. I could put it in a share folder under one of the MINGW location like MINGW64 or UCRT64.
Or, I could make an new location to put it; if a new location I would prefer someone else chose the name.

Tim S.

**Comment by mmuetzel** [comment]
> I mostly agree; but, had no idea where else to put it. I could put it in a share folder under one of the MINGW location like MINGW64 or UCRT64.

I don't think the native environments should cross-reference like this either.
MSYS2 is sometimes also used as a base to create "re-distributable packages" for one software. (Think of "Git for Windows" or others.) It would be strange if they'd need to "mix" installations in different environments to get to a working software.

> Or, I could make an new location to put it; if a new location I would prefer someone else chose the name.

What is the main goal of this idea? Reduce the size of the packages on the MSYS2 mirrors? Or reduce the size of the installation on the user side?
If it is the latter: How many users actually install the same software in multiple environments (apart from testers or packagers)? (To be honest: I do that. But I'd count myself to the testers and packagers group.) A "normal" user of the software probably only installs it once in one single environment.
If it is the former: Do we need to worry about that?

**Comment by lazka** [comment]
This package here at least is 385MB per env. Not sure that's enough to warrant anything special

**Comment by stahta01** [comment]
> This package here at least is 385MB per env. Not sure that's enough to warrant anything special

Okay I will close this PR; I thought it was much bigger.

**Pull request closed without merging**
