### PR TITLE
msys2-runtime: Update patches

### PR DESCRIPTION
**Pull request by lazka**
See https://github.com/msys2/msys2-runtime/pull/15

### CODE REVIEW

**Review by dscho — APPROVED** [review]

**Comment by nga888** [comment]
I recently ran into an issue with broken output with pseudo console enabled, i.e. `MSYS=enable_pcon`, and I traced it back to this change.

Shouldn't the setting of the console codepage at the end of `setup_local` be conditional on pseudo console being disabled as suggested by @tyan0 in https://github.com/msys2/MSYS2-packages/issues/1974#issuecomment-686837959?

**Comment by dscho** [comment]
> I recently ran into an issue with broken output with pseudo console enabled, i.e. `MSYS=enable_pcon`, and I traced it back to this change.

Would you be able to provide *some* sort of detail?

> Shouldn't the setting of the console codepage at the end of `setup_local` be conditional on pseudo console being disabled as suggested by @tyan0 in https://github.com/msys2/MSYS2-packages/issues/1974#issuecomment-686837959?

We specifically did *not* do that, in order to fix the reported issue both with enabled *and* with disabled support for Pseudo Consoles.

**Comment by nga888** [comment]
> Would you be able to provide _some_ sort of detail?

Sorry, I do not have a simple reproducible, all I've managed to determine so far is that without this change my problem goes away. It's a work related testing system that I run from bash in mintty that runs native python, NAnt and various native applications that also involves redirection of stdin/stdout.

> We specifically did _not_ do that, in order to fix the reported issue both with enabled _and_ with disabled support for Pseudo Consoles.

I did see mention of this in that thread, but the reproducible for that issue works fine for me with pseudo console enabled. I think @tyan0 also said it worked for him too, IIRC.

Sorry that I can't provide any more useful info. If I get time to investigate further, I'll follow up. For now, I'm fine with my patched version of the runtime and I'm probably in the minority that run with pseudo console enabled.

**Comment by dscho** [comment]
> Sorry, I do not have a simple reproducible, all I've managed to determine so far is that without this change my problem goes away.

Unfortunately, this is saying something like "you have a bug, but I won't tell you anything about it, so you cannot fix it either"

Could you _at least_ talk about the symptoms you are seeing?

As far as anybody on this side of the report can tell, the bug might be in your testing system. Or it might be in the MSYS2 runtime. Or in the Cygwin portion of the code. Nobody except for you has enough information to tell...

**Comment by nga888** [comment]
> Unfortunately, this is saying something like "you have a bug, but I won't tell you anything about it, so you cannot fix it either"
> 
> Could you _at least_ talk about the symptoms you are seeing?

I would normally do more investigation before commenting, but in this case I saw that the author of the original code had already suggested the change that would address my issue, which is why I asked the question. But as it was a conscience decision to go with the current patch, then I have no complaints.

As far as symptoms are concerned, it appears that output/input is getting "corrupted" somewhere between the native applications, but I haven't had time to pinpoint where and how.

> As far as anybody on this side of the report can tell, the bug might be in your testing system. Or it might be in the MSYS2 runtime. Or in the Cygwin portion of the code. Nobody except for you has enough information to tell...

Yes, without further information and investigation, it is hard to know what might be at fault. However, this is a "legacy" testing system that has not changed for a very long time and was running fine until this patch. Unfortunately, as I mentioned before, I don't really have the time now to investigate this in more detail. If I do get time to look into this in more detail, I'll follow up if appropriate.

Sorry for any unnecessary noise caused.

**Comment by dscho** [comment]
> > We specifically did _not_ do that, in order to fix the reported issue both with enabled _and_ with disabled support for Pseudo Consoles.
> 
> I did see mention of this in that thread, but the reproducible for that issue works fine for me with pseudo console enabled. I think @tyan0 also said it worked for him too, IIRC.

I could _not_ replicate the findings. In my hands, the patch was required to fix both `disable_pcon`/`enable_pcon`. That is why I contributed the patch in the current form, and unless I get some tangible evidence where the patch does anything unintended, I'll remain unconvinced.

**Comment by nga888** [comment]
FYI I managed to find some time to look into this and my problem arises due to the way NAnt feeds input to stdin when executing a program. When the code page is set to 65001, it prefixes a BOM to the input stream and this causes a problem if the receiving program does not expect this. When the code page is 850 (my default) it works fine.

So my problem does arise as a side-effect of this patch. However, what's the "real" problem is not so clear, as many of the older native programs do not support UTF-8 and it's also quite unusual to have a BOM for UTF-8.

**Pull request merged**
