### PR TITLE
Upgrade the MSYS2 runtime to v3.3.3

### PR DESCRIPTION
**Pull request by dscho**

### CODE REVIEW

**Comment by piotrvv** [comment]
Can you change the [0001-Add-MSYS2-triplet.zip](https://github.com/msys2/MSYS2-packages/files/7654146/0001-Add-MSYS2-triplet.zip) file to mine and try building the package again. As the gcc package was built in.

**Comment by MehdiChinoune** [comment]
```diff
--- a/config.guess
+++ b/config.guess
@@ -914,6 +914,9 @@ EOF
     amd64:CYGWIN*:*:* | x86_64:CYGWIN*:*:*)
 	echo x86_64-pc-cygwin
 	exit ;;
+    amd64:MSYS*:*:* | x86_64:MSYS*:*:*)
+	echo x86_64-unknown-msys
+	exit ;;
     prep*:SunOS:5.*:*)
 	echo powerpcle-unknown-solaris2"$(echo "$UNAME_RELEASE"|sed -e 's/[^.]*//')"
 	exit ;;
```
Why not `x86_64-pc-msys` like `x86_64-pc-cygwin` above it?

**Comment by dscho** [comment]
> Can you change the [0001-Add-MSYS2-triplet.zip](https://github.com/msys2/MSYS2-packages/files/7654146/0001-Add-MSYS2-triplet.zip) file to mine and try building the package again. As the gcc package was built in.

Please open a PR with a `fixup!` over at msys2/msys2-runtime, for _proper_ review.

**Comment by dscho** [comment]
> ```diff
> --- a/config.guess
> +++ b/config.guess
> @@ -914,6 +914,9 @@ EOF
>      amd64:CYGWIN*:*:* | x86_64:CYGWIN*:*:*)
>  	echo x86_64-pc-cygwin
>  	exit ;;
> +    amd64:MSYS*:*:* | x86_64:MSYS*:*:*)
> +	echo x86_64-unknown-msys
> +	exit ;;
>      prep*:SunOS:5.*:*)
>  	echo powerpcle-unknown-solaris2"$(echo "$UNAME_RELEASE"|sed -e 's/[^.]*//')"
>  	exit ;;
> ```
> Why not `x86_64-pc-msys` like `x86_64-pc-cygwin` above it?

Because the MSYS2 runtime uses this for over five years already. If you want to change it _now_, you will have to present very, very, _very_ convincing arguments, or it simply won't happen. Would break too much.

**Comment by jeremyd2019** [comment]
Wait, what is that trying to fix?

**Comment by MehdiChinoune** [comment]
> > ```diff
> > --- a/config.guess
> > +++ b/config.guess
> > @@ -914,6 +914,9 @@ EOF
> >      amd64:CYGWIN*:*:* | x86_64:CYGWIN*:*:*)
> >  	echo x86_64-pc-cygwin
> >  	exit ;;
> > +    amd64:MSYS*:*:* | x86_64:MSYS*:*:*)
> > +	echo x86_64-unknown-msys
> > +	exit ;;
> >      prep*:SunOS:5.*:*)
> >  	echo powerpcle-unknown-solaris2"$(echo "$UNAME_RELEASE"|sed -e 's/[^.]*//')"
> >  	exit ;;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why not `x86_64-pc-msys` like `x86_64-pc-cygwin` above it?
> 
> Because the MSYS2 runtime uses this for over five years already. If you want to change it _now_, you will have to present very, very, _very_ convincing arguments, or it simply won't happen. Would break too much.

I have changed it for both gcc and binutils!
https://github.com/msys2/MSYS2-packages/pull/2716/files#diff-54b6d026e7e36b1645fe0faecb1303c3fa0c969f7c059f597ede13452bca00c8L526
https://github.com/msys2/MSYS2-packages/pull/2715/files?authenticity_token=3ceEpnT8odCC432eo7qSiyWM9tjMLy1YfIkD90%2F5xquBWKKtukx5iEG9SHHxzLhVgkQLmxbs6I66a65k0otiow%3D%3D&file-filters%5B%5D=.patch&file-filters%5B%5D=No+extension#diff-c248cb3e54b54bda8c06ce88f8ccebaccdd259d4b3d5bd0304727ca6fcbf46feL121

**Comment by dscho** [comment]
> > > ```diff
> > > --- a/config.guess
> > > +++ b/config.guess
> > > @@ -914,6 +914,9 @@ EOF
> > >      amd64:CYGWIN*:*:* | x86_64:CYGWIN*:*:*)
> > >  	echo x86_64-pc-cygwin
> > >  	exit ;;
> > > +    amd64:MSYS*:*:* | x86_64:MSYS*:*:*)
> > > +	echo x86_64-unknown-msys
> > > +	exit ;;
> > >      prep*:SunOS:5.*:*)
> > >  	echo powerpcle-unknown-solaris2"$(echo "$UNAME_RELEASE"|sed -e 's/[^.]*//')"
> > >  	exit ;;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Why not `x86_64-pc-msys` like `x86_64-pc-cygwin` above it?
> > 
> > Because the MSYS2 runtime uses this for over five years already. If you want to change it _now_, you will have to present very, very, _very_ convincing arguments, or it simply won't happen. Would break too much.
> 
> I have changed it for both gcc and binutils!
> https://github.com/msys2/MSYS2-packages/pull/2716/files#diff-54b6d026e7e36b1645fe0faecb1303c3fa0c969f7c059f597ede13452bca00c8L526
> https://github.com/msys2/MSYS2-packages/pull/2715/files?authenticity_token=3ceEpnT8odCC432eo7qSiyWM9tjMLy1YfIkD90%2F5xquBWKKtukx5iEG9SHHxzLhVgkQLmxbs6I66a65k0otiow%3D%3D&file-filters%5B%5D=.patch&file-filters%5B%5D=No+extension#diff-c248cb3e54b54bda8c06ce88f8ccebaccdd259d4b3d5bd0304727ca6fcbf46feL121

I am really concerned how many existing users you might have broken with this seemingly nilly-willy change. _Really_ concerned.

In any case, a PR that rebases existing (and well-reviewed) patches is a _terrible_ place to start a fundamental discussion like this. Open a PR in the correct repository, which is msys2/msys2-runtime. Or start a discussion in the chat. But don't hide such a profound questioning of existing practices deep inside an already-merged PR.

**Comment by dscho** [comment]
It would probably also be a splendid idea to strip URLs of their `authenticity_token` before posting them publicly.

**Comment by MehdiChinoune** [comment]
I am not discussing about changing the default triplet, I think you have much more experience than me with these things.
I am asking if it is required to change the triplet of gcc and binutils back to x86_64-unknown-msys.

**Comment by dscho** [comment]
Again, this PR, which was already merged, is a _terrible_ place to have this conversation.

**Comment by lazka** [comment]
(Reverted in master: 3e14b95280f5d98c)

**Comment by jeremyd2019** [comment]
> (Reverted in master: [3e14b95](https://github.com/msys2/MSYS2-packages/commit/3e14b95280f5d98c32efbdf7ea6c1ce3f72ed050))

To be clear, this "revert" is in reference to the triplet change in binutils/gcc. *not* to this PR.

**Pull request merged**
