### PR TITLE
msys2-runtime: upgrade to v3.4.0

### PR DESCRIPTION
**Pull request by dscho**
This is a companion to https://github.com/msys2/msys2-runtime/pull/120

### CODE REVIEW

**Comment by lazka** [comment]
thanks, I was wondering if we should create a separate "msys2-runtime-3.4" for this to allow some testing.

**Comment by dscho** [comment]
@lazka I like how you're intending to play it safe. But I think v3.4 _should_ be relatively stable. Having a passing `path_convert` test run would of course give me more confidence ;-)

**Comment by lazka** [comment]
OK, thanks for your judgement.

I remember various low level changes when following git changes and IRC, which is why I'm cautious (but also didn't see any issues/reports pop up there). ok, I'll look into some testing then.

**Comment by dscho** [comment]
Your caution was merited, apparently ☺

**Comment by lazka** [comment]
All .exe try to link to `cygwin1.dll`, so something is wrong there.

**Comment by dscho** [comment]
Sorry about that, I thought I had resolved all merge conflicts.

Now I think I want to verify that there were no other instances of a `*-x86_64` file being renamed, and me re-adding it by mistake...

**Comment by lazka** [comment]
> Sorry about that, I thought I had resolved all merge conflicts.

no prob

> Now I think I want to verify that there were no other instances of a `*-x86_64` file being renamed, and me re-adding it by mistake...

I didn't notice anything looking through the diff at least.

This is superseded by #3393 and #3394 now, so closing.

**Comment by dscho** [comment]
There is _one_ thing we'll want to salvage from this here PR: the change to exclude CI-only patches from `update-patches.sh`.

**Comment by lazka** [comment]
> There is _one_ thing we'll want to salvage from this here PR: the change to exclude CI-only patches from `update-patches.sh`.

I used this PR as a base for msys2-runtime-3.4, so that should have survived.

**Comment by dscho** [comment]
> > There is _one_ thing we'll want to salvage from this here PR: the change to exclude CI-only patches from `update-patches.sh`.
> 
> I used this PR as a base for msys2-runtime-3.4, so that should have survived.

[So they did](https://github.com/lazka/MSYS2-packages/commit/c0957bb2a7a8ddd49185d98eaf2c57d615491560#diff-2ff19ca3a2158ad26477b1483ef23e56878057d4369516a3faf257de02dc35c9R48). (I was on a phone and could not easily check that out yesterday, but today I could.)

**Pull request closed without merging**
