### PR TITLE
Update mingw-w64 packages to commit 1c7738.

### PR DESCRIPTION
**Pull request by jeremyd2019**
This should include fixes for msys2/CLANG-packages#6 and
msys2/CLANG-packages#21

### CODE REVIEW

**Comment by jeremyd2019** [comment]
CI failed due to a blip cloning from sf's git server.  But, CI fails anyway due to conflicts between the clang, ucrt, and 'normal' versions of the mingw-w64-cross packages, because the CI script installs all packages after building.  If desired, I can split this into 3 pull requests that can each pass CI.

**Comment by Biswa96** [comment]
Passing CI here would not make any difference. The can be merged as is because mingw-w64 toolchain will not fail to build 🤞

**Comment by jeremyd2019** [comment]
Well, I've been doing some building with this revision, and ran into a regression in ucrt: https://sourceforge.net/p/mingw-w64/mailman/message/37257645/

Namely, fseterr.c from gnulib now fails to compile, because it tries to mess with the _flag field in the FILE*

**Comment by jeremyd2019** [comment]
Issue I ran into is now fixed.  PR updated to newer commit that fixes it.

**Comment by jeremyd2019** [comment]
Once this is merged (or at least the mingw-w64-cross-clang packages, I can split them if that's more palatable) I intend to update/rebase #2294, and once that and #2426 are merged I can at least get msys2/CLANG-packages#2 building an aarch64 hosted and targeting clang in CI.

**Comment by lazka** [comment]
We need to move CI to use a temporary repository instead of installing everything in the PR.

**Pull request merged**
