### PR TITLE
grep: Update to 3.5

### PR DESCRIPTION
**Pull request by jannick0**
* grep/PKGBUILD:
  - update version and hash
  - remove references to outdated and obsolete patches
  - build binary in separate directory
* grep/{grep-2.23-msys2.patch,grep-3.0-2.patch}: remove files

### CODE REVIEW

**Comment by Biswa96** [comment]
Are those patches in upstream repository? If yes then a commit message with that upstream commit link would be helpful.

**Comment by Alexpux** [comment]
It not possible to update grep for MSYS2 as upstream drop support for crlf. So I hope it will not be merged

**Comment by Alexpux** [comment]
here is commit:
https://git.savannah.gnu.org/cgit/grep.git/commit/?id=5ac3d87a69122d45a837840914c2f9e66b5bb8d4

**Comment by jannick0** [comment]
@Alexpux  I fully agree that grep is a central piece to MSYS2. Yesterday I was not aware of this severe issue. 

* The documentation (changed in the commit you are pointing to - thanks) does not read very clear to me (highlilghts from me):

Under MS-Windows, use binary I/O when reading and writing files **other
than the user's terminal**, so that all input bytes are read and written
as-is.  This overrides the default behavior where @command{grep}
follows the operating system's advice whether to use binary or text
I/O.

* grep-3.0-2.src.patch cannot be reverted in the source of grep-3.5, since the target source file is removed meanwhile.  So the much feared change does not show up in the source anymore.   
* I am confused about grep's expected vs actual CRLF/LF handling now: What should grep do and what shouldn't it do (test cases?) with respect to  `-U`, CRLF/LF in shell MSYS2/MINGW64/MINGW32,..., which input to grep?

Or am I missing something here?

**Comment by Alexpux** [comment]
@jannick0 look at https://github.com/msys2/MSYS2-packages/issues/1353

**Pull request closed without merging**
