### PR TITLE
pkgconf: Update to 2.0.3

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by dg0yt** [comment]
We need 2.1.0 now!

**Comment by dg0yt** [comment]
(All 2.0 releases are broken due to https://github.com/pkgconf/pkgconf/issues/322.)

**Comment by MehdiChinoune** [comment]
> We need 2.1.0 now!

Are you using pkgconf or mingw-w64-pkgconf, I think vcpkg uses the latter

**Comment by dg0yt** [comment]
> Are you using pkgconf or mingw-w64-pkgconf, I think vcpkg uses the latter

Good question. 
It uses the mingw versions for general PKGCONFIG purposes (e.g. via CMake). 
But it always carried msys pkg-config, now pkgconf, as a default package for the autotools build environment. And it works.

**Pull request merged**
