### PR TITLE
xxhash: Update to 0.8.0

### PR DESCRIPTION
**Pull request by jannick0**

### CODE REVIEW

**Comment by lazka** [comment]
The DLL name changed, so the dependent packages need their pkgrel increased. In this case it's only rsync.

**Comment by jannick0** [comment]
@lazka Thanks for this!

BTW: I am intrigued by the problem to identify that the dll interface version changed (which is the case here at hand).  Do you have any tool on the shelves to be alerted when a dll file name is changed?

**Comment by lazka** [comment]
There are no tools atm. I just looked at https://packages.msys2.org/package/libxxhash?repo=msys&variant=x86_64 to see if the version is encoded int he DLL name.

**Comment by jannick0** [comment]
@lazka Best if CI could run this look up job I think. I'll see if I can come up with something soon.

**Pull request merged**
