### PR TITLE
remove gcc-fortran

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
What's the motivation here?

Arch has it in checkdepends.

**Comment by MehdiChinoune** [comment]
> What's the motivation here?
> 
> Arch has it in checkdepends.

I have removed it from gcc in #4043 because gfortran is not needed on MSYS environment.

**Comment by lazka** [comment]
Did it not build?

**Comment by MehdiChinoune** [comment]
> Ah, I see, did it not build?

I said I do disabled Fortran because is not required.

**Comment by lazka** [comment]
Alright, fair enough.

**Pull request merged**
