### PR TITLE
gnupg: Update to 2.4.3

### PR DESCRIPTION
**Pull request by lazka**
* drop patch included in the new release
* backport build fix
* sync patches from Arch

### CODE REVIEW

**Comment by lazka** [comment]
Let's wait until Arch makes the switch: https://archlinux.org/packages/core/x86_64/gnupg/

**Comment by jeremyd2019** [comment]
FYI https://mailarchive.ietf.org/arch/msg/openpgp/AY0KIJS5yrAqeaEWAs351A4bXnM/

I don't want to get into the debate/flamewar behind the apparent schism between gnupg and the openpgp wg at ietf, I don't entirely understand the issues, but something to be aware of.

**Comment by lazka** [comment]
thanks. yeah those are the patches I meant: https://gitlab.archlinux.org/archlinux/packaging/packages/gnupg

**Comment by lazka** [comment]
used it for a few days, all seems to work

**Comment by lazka** [comment]
New gnupg doesn't like Alexey's key, I had to revert it for now:

```
error: perl-Error: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is marginal trust
:: File /var/cache/pacman/pkg/perl-Error-0.17029-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
error: perl-LWP-MediaTypes: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is marginal trust
Do you want to delete it? [Y/n] 
:: File /var/cache/pacman/pkg/perl-LWP-MediaTypes-6.04-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: perl-WWW-RobotRules: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is marginal trust
Do you want to delete it? [Y/n] 
:: File /var/cache/pacman/pkg/perl-WWW-RobotRules-6.02-2-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
error: perl-MailTools: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is marginal trust
Do you want to delete it? [Y/n] 
:: File /var/cache/pacman/pkg/perl-MailTools-2.21-1-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
error: perl-IO-Stringy: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is marginal trust
Do you want to delete it? [Y/n] 
:: File /var/cache/pacman/pkg/perl-IO-Stringy-2.113-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
error: failed to commit transaction (invalid or corrupted package)
Do you want to delete it? [Y/n] 
```

**Comment by lazka** [comment]
Summary here: https://github.com/msys2/MSYS2-keyring/issues/45

**Comment by lazka** [comment]
Also some LWN article on the patch backgrounds: https://lwn.net/SubscriberLink/953797/7222cd75661fb888/

**Pull request merged**
