### PR TITLE
aspell-de: new package (version 20161207)

### PR DESCRIPTION
**Pull request by jannick0**

### CODE REVIEW

**Comment by jannick0** [comment]
Just realized that this PR is a dublicate of PR #1791 . If one of the PRs is merged, the other could be closed.  I have not checked the other PR.

**Comment by lazka** [comment]
Just wondering, how/with what are you using aspell?

**Comment by jannick0** [comment]
I run text documents in one or more languages against `aspell` for spell checking in an automized way and - if any unknown words are found - `aspell` can output a list of unknown items which after (manual) amendment can be used to fix the spelling problems of the document (with `aspell` again).  
Fortunately, `aspell` is smart enough to handle (most of the) inflection features in line with the language grammar. In addition, `aspell` can handle structured documents, e.g. `LaTeX` docs, by focussing on the text and ignoring the dangling commands. 

More here: http://aspell.net.

**Comment by jannick0** [comment]
@lazka Many thanks!

#1791 could be closed now, I think, since obsolete after this merge.

**Pull request merged**
