### PR TITLE
filesystem/main-config.site: fixed missing newline

### PR DESCRIPTION
**Pull request by Karlson2k**
A simple fix for broken output in config.log.

Currently log looks like:
``` log
configure:2671: loading site script /etc/config.site
| # This file is in public domain.
| # Original author: Karlson2k (Evgeny Grin)
[[ skipped ]]
| ficonfig.site:13: default build_alias set to x86_64-w64-mingw32
config.site:20: default prefix set to /clang64
configure:3086: looking for aux files: config.rpath ltmain.sh compile config.guess config.sub missing install-sh

```

### CODE REVIEW

**Comment by lazka** [comment]
What's the expected output? And what does this change?

Anyway, needs a pkgrel bump and checksum updates.

**Comment by Karlson2k** [comment]
1. All scripts must end with a newline. While bash and most of GNU tools can tolerate absence of missing newline, it still can produced unexpected results.
2. In this particular case, the result is mostly harmless: final line from `config.site` is combined with the next log line. 
Currently it is:
```
| ficonfig.site:13: default build_alias set to x86_64-w64-mingw32
config.site:20: default prefix set to /clang64
```
Should be:
```
| fi
config.site:13: default build_alias set to x86_64-w64-mingw32
config.site:20: default prefix set to /clang64
```
I'll update with bump and checksum.

**Comment by lazka** [comment]
ok, I see, thanks

**Comment by Karlson2k** [comment]
@lazka Updated with pkgrel bump and new checksum.

**Comment by Karlson2k** [comment]
@lazka Updated with pkgrel bump and new checksum.

**Pull request merged**
