### PR TITLE
coreutils: update to 9.4

### PR DESCRIPTION
**Pull request by MehdiChinoune**
patches were copied from CygWin.

### CODE REVIEW

**Comment by lazka** [comment]
Some fallout: https://github.com/msys2/MINGW-packages/pull/18565

I'm not sure yet what/why, but I can reproduce locally.

**Comment by MehdiChinoune** [comment]
Feel free to revert it, I don't think I have enough knowledge and time to investigate and fix it.

**Comment by lazka** [comment]
Fair enough.

Atm it's still the only package that has issues. We should try building the toolchains and the runtime though as well before releasing it from staging.

**Comment by MehdiChinoune** [comment]
Packaging newlib for arm and riscv targets also fails.

**Comment by lazka** [comment]
I think the problem is that `cygwin_spelling()` is called with destination relative paths in some places, but cygwin_spelling() doesn't deal with them.

I think we should (1) revert this for now (2) update to 9.0 instead which is actively used in cygwin, and is before coreutils switched to destination relative paths.

I've emailed Brian Inglis about my findings.

**Pull request merged**
