### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by neheb** [comment]
Curious. Why does file not include libmagic?

**Comment by Biswa96** [comment]
> Curious. Why does file not include libmagic?

Answer https://en.wikipedia.org/wiki/File_(command)

**Comment by neheb** [comment]
On Wed, Mar 31, 2021 at 10:33 PM Biswapriyo Nath ***@***.***>
wrote:

> Curious. Why does file not include libmagic?
>
> Answer https://en.wikipedia.org/wiki/File_(command)
>
Sure but libmagic is a separate library that other programs use. It doesn't
seem packaged with file.

**Comment by Biswa96** [comment]
file(1) already has those things in source which is compiled as msys-magic-1.dll.

**Comment by neheb** [comment]
Ah I see. It's MSYS only. No MinGW.

**Pull request merged**
