### PR TITLE
New Package: GNU Stow v2.3.1

### PR DESCRIPTION
**Pull request by tavrez**

### CODE REVIEW

**Comment by lazka** [comment]
What's is this needed for?

**Comment by tavrez** [comment]
It's a great application for handling symlink files, used for managing dotfiles https://dotfiles.github.io/

**Comment by 1480c1** [comment]
I am sort of curious is gnu stow would be good at all since we can't make symlinks (as in actual symlinks) without either admin power or dev mode

**Comment by siprbaum** [comment]
I agree that this needs admin or developer mode, but considering that cygwin is usually used by people I consider power users,
the chances are very high that these permissions are available.

So I would appreciate having this in and would definitely use it for my dotfile handling like I used to under linux

**Comment by tavrez** [comment]
I should also say that stow(and ln) use hard links by default. And hard links does not need admin permission or developer mode.

**Comment by soredake** [comment]
Any progress on this?

**Comment by fralalonde** [comment]
GNU Stow is an critical component of many `.dotfiles` setup. It allows things like storing and recreating your environment from a personal git repo. It is a simple, safe and important component of a modern distribution.

Please merge this.

**Comment by fralalonde** [comment]
I see this has been merged, thanks! 

Just to confirm, I've meanwhile installed `stow` manually from the submitter's branch (using `makepkg`). I then used it to deploy my own dotfiles and it ran without a hitch. I'll reinstall from the now-official pkg on my next update.

**Pull request merged**
