### PR TITLE
Clang Subversion repo deprecated

### PR DESCRIPTION
**Pull request by walker27460**

### CODE REVIEW

**Comment by hiroakit** [comment]
It's cool PR!
BTW, Where did you get this information?
> Clang Subversion repo deprecated

**Comment by pal1000** [comment]
> 
> 
> It's cool PR!
> BTW, Where did you get this information?
> 
> > Clang Subversion repo deprecated

There are multiple places from where @walker27460 could have learned about this:
- [LLVM Getting Started docs](https://llvm.org/docs/GettingStarted.html#checkout-via-svn-deprecated);
- a Github migration being complete note on llvm.org home page;
- llvm-dev mailing list;
- mingw package counterpart.

I personally known about llvm migration to git since it was WIP,  This wasn't a big secret.

**Comment by walker27460** [comment]
Yes, I learned from GitHub migration being complete note.
BTW,when I tried to submit the package,CI Check told me can’t use pkgver in package function.
Any ideas?

**Comment by pal1000** [comment]
This should help: https://github.com/msys2/MINGW-packages/commit/5ee34d7ddf187f9d61daddee8d7aa4c121b7a1d1#diff-f8431e29bf404d2b6e837a3e6a7e6b00

**Comment by walker27460** [comment]
When I checked manpage of PKGBUILD, I've found overriding pkgver in split package support is removed in the latest pacman version.
So, we can't define different version in split package.

**Comment by hiroakit** [comment]
NOTE:
1. [The SVN repository is no longer updated, but it is still available for now. (LLVM Getting Started docs)](https://llvm.org/docs/GettingStarted.html#checkout-via-svn-deprecated)
2. [Moving LLVM Projects to GitHub](https://llvm.org/docs/Proposals/GitHubMove.html)
2. [The LLVM Compiler Infrastructure Project](http://llvm.org/GitHubMigrationStatus.html)

**Comment by hiroakit** [comment]
@walker27460

Thank you for your updating.
I would like to confirm about the error which occurred in CI.

## Q1. Is the error it? 

[CI build log](https://dev.azure.com/msys2/mingw/_build/results?buildId=4575&view=logs&j=17d3025b-59e7-5db6-c663-923517b33a7c&t=830f4cfb-de6c-520f-5d2e-ce0dea5896af) is here.

```
[MSYS2 CI] clang-svn: Building binary

==> ERROR: pkgver can not be set inside a package function
==> ERROR: pkgver can not be set inside a package function

[MSYS2 CI] FAILURE: clang-svn: Building binary failed.

##[error]Cmd.exe exited with code '1'.
```

## Q2. Did you get the same error when run makepkg on your local machine?

Step is here.

```
$ git clone https://github.com/walker27460/MSYS2-packages.git walker27460_MSYS2-packages
$ cd walker27460_MSYS2-packages
$ git checkout -b patch-3 origin/patch-3
$ cd clang-svn
$ makepkg
==> ERROR: pkgver can not be set inside a package function
==> ERROR: pkgver can not be set inside a package function
```

## Q3. What version do you use the pacman? v5.2.1?

My machine has the pacman v5.2.1, log is here.

```
$ pacman --version

 .--.                  Pacman v5.2.1 - libalpm v12.0.1
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2019 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

**Comment by walker27460** [comment]
A1: Yes,it is.
A2: I got same error on CI.

**Comment by walker27460** [comment]
I just pushed close button accidenttally. Sorry for that.

**Comment by walker27460** [comment]
Error occurred at patching.
```
error: cmake/modules/AddLLVM.cmake: does not exist in index
error: cmake/modules/HandleLLVMOptions.cmake: does not exist in index
error: lib/Transforms/Hello/CMakeLists.txt: does not exist in index
hint: Use 'git am --show-current-patch' to see the failed patch
Applying: cmake hack for msys2
Patch failed at 0001 cmake hack for msys2
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by walker27460** [comment]
then it says `Makefile.config.in` file not found.

**Comment by hiroakit** [comment]
Late sharing, this page helpful?

ArchLinux packages/llvm PKGBUILD 
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/llvm

**Comment by Alexpux** [comment]
clang-svn package currently not maintained and removed from pacman database. Use mingw clang instead

**Comment by walker27460** [comment]
Then may I remove this PKGBUILD and patches from repository?

**Comment by Alexpux** [comment]
I’m already do it locally, will push later

**Comment by walker27460** [comment]
Closed.

**Pull request closed without merging**
