### PR TITLE
Add new lcov package

### PR DESCRIPTION
**Pull request by lazka**
See https://github.com/Alexpux/MINGW-packages/issues/3156

### CODE REVIEW

**Comment by lazka** [comment]
@yumetodo why the "confusion" ?

**Comment by yumetodo** [comment]
To use for mingw32/mingw64, how to use this patch?

In my understanding, the answer is nothing.

I cannot understand why adding lcov as msys2 package, not mingw32/mingw64, resolve https://github.com/Alexpux/MINGW-packages/issues/3156.

**Comment by lazka** [comment]
> To use for mingw32/mingw64, how to use this patch?

`pacman -S lcov` and then use lcov as usual, once it is in the repo.

> In my understanding, the answer is nothing.

It works for gcov coverage files produced by mingw gcc. What do you think wouldn't work?

**Comment by lazka** [comment]
@Alexpux any objections?

**Comment by lazka** [comment]
Updated to 1.14 which adds gcc8 support

**Comment by lazka** [comment]
1.14 doesn't support gcc9 and upstream doesn't plan to do a release supporting gcc9 [0], so closing.

[0] https://github.com/linux-test-project/lcov/issues/58#issuecomment-522967473

**Pull request closed without merging**
