### PR TITLE
cmake: Update to 3.20.0

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by lazka** [comment]
Could you briefly describe your patch changes? why/what etc..

**Comment by orgads** [comment]
Sure. `perl-libs` is unused. I merged `disable-response-files` into the large patch, applied it on top of cmake 3.20, resolved conflicts and recreated it with Git (and renamed it because the version number was misleading).

**Comment by lazka** [comment]
I see, thanks!

**Comment by orgads** [comment]
I also filed a [MR for cmake](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5933) with this patch, to ease later updates.

**Pull request merged**
