### PR TITLE
msys2-runtime: avoid "Bad address" errors in the MSYS2 path conversion

### PR DESCRIPTION
**Pull request by dscho**
This commit corresponds to https://github.com/msys2/msys2-runtime/pull/179 and should fix https://github.com/msys2/MSYS2-packages/issues/2282 and maybe even https://github.com/microsoft/vcpkg/pull/34274.

### CODE REVIEW

**Comment by dg0yt** [comment]
Two more fixup patches here? Shouldn't the commits have better been squashed when merged to msys2-runtime? 
I'm planning to submit more changes to reduce the number of allocations... and I often keep individual changes as individual commits in one PR, for PR review purposes.

**Comment by lazka** [comment]
The PKGBUILD is just a straight mirror of the active branch of msys2/msys2-runtime. In msys2/msys2-runtime we only squash when we rebase for a new version to not break the existing history.

**Comment by dscho** [comment]
> Two more fixup patches here?

Yes. To allow for easier collaboration, we never force-push `msys2-<version>` branches in https://github.com/msys2/msys2-runtime.

And as @lazka pointed out, we only every update the patches in this repository's `msys2-runtime/` subdirectory via the `update-patches.sh` script (I always meant to add some automation that I could easily kick off from a merged msys2/msys2-runtime PR to create the corresponding msys2/MSYS2-packages PR, but never got around to doing that). The reason is that it is much easier to build confidence in the correctness that way.

> Shouldn't the commits have better been squashed when merged to msys2-runtime?

Yes! And we will do that when the next Cygwin version is released: Then, we will create a new `msys2-<new-version>` branch that points at the Cygwin revision, then rebase the commits from the previous `msys2-<version>` branch, push them as `tentative/msys2-<new-version>` and open a PR in msys2/msys2-runtime for cross-validation by other team members.

That rebase will be performed with `--auto-squash` and everything will get neat and tidy again.

> I'm planning to submit more changes to reduce the number of allocations...

Looking forward to them!

> and I often keep individual changes as individual commits in one PR, for PR review purposes.

Excellent. I like well-prepared PRs like that.

**Comment by dscho** [comment]
I guess there is room for explanation in [msys2-runtime's `README`](https://github.com/msys2/msys2-runtime#readme)...

**Comment by lazka** [comment]
It's documented here, somewhat: https://github.com/msys2/msys2-runtime/wiki

**Comment by dg0yt** [comment]
Well, I really had to pull together pieces from different sources until I was able to arrive at testable packages.

**Comment by lazka** [comment]
yeah, lots of room for improvements there

**Comment by lazka** [comment]
It's in the pacman repo now

**Comment by dg0yt** [comment]
vcpkg CI is happy :tada:

**Pull request merged**
