### PR TITLE
automake1.17: new package

### PR DESCRIPTION
**Pull request by ikspress**
This package is based on automake1.16
Difference between automake1.17 and 1.16
- Rename `README.am17` to `README.am1.17`
- Add more `checkdepends`

If you're not satisfied with any changes I've made, feel free to leave feedback.

### CODE REVIEW

**Comment by Biswa96** [comment]
Why do you need that specific version?

**Comment by ikspress** [comment]
> Why do you need that specific version?

Oh, I just want make it easier for future update. It not necessary for me.

**Comment by ikspress** [comment]
I've revert README.am17 back. Please squash merge if you satisfied with this package.

**Comment by ikspress** [comment]
Please don't forget to update `autotools-wrappers`. :)

**Comment by lazka** [comment]
thanks

**Comment by ikspress** [comment]
> thanks

Oh, hey, lazka. You were forgot to remove [0001-bump-latest-autoconf-version.patch](https://github.com/msys2/MSYS2-packages/blob/cdfdf7a56b7ad44450576f48b5defa5b8bf6556e/autotools-wrappers/0001-bump-latest-autoconf-version.patch).

**Comment by lazka** [comment]
thanks, fixed

**Pull request merged**
