### PR TITLE
libtool: support `llvm-objdump -f` output

### PR DESCRIPTION
**Pull request by mati865**
More info in https://github.com/msys2/CLANG-packages/issues/9

### CODE REVIEW

**Comment by lazka** [comment]
adding a validpgpkeys array should fix that

**Comment by mati865** [comment]
Tests will fail if they are ran on the CI though and I couldn't figure what is wrong with them.

**Comment by mati865** [comment]
Oh, `check()` is not ran on the CI.

**Comment by jeremyd2019** [comment]
I don't know why, but gmp seems to be trying to use a linker script now on i686.

**Comment by jeremyd2019** [comment]
It kind of looks like the ltmain.sh installed in the package is lacking some of the other clang-related patches that were already there

**Comment by jeremyd2019** [comment]
Ah, the new patch patches ltmain.sh, making it newer than ltmain.in which the other patches patched, causing ltmain.sh not to be regenerated from ltmain.in.

**Comment by mati865** [comment]
Okay, now I hate autotools even more than usually. So reordering the patches would help?

**Comment by jeremyd2019** [comment]
Just patch ltmain.in instead of ltmain.sh

**Comment by mati865** [comment]
Ah, I have modified `.sh` instead of `.in`. Nice catch.

**Pull request merged**
