### PR TITLE
inetutils: Update to 2.5

### PR DESCRIPTION
**Pull request by lazka**
sync with cygwin

### CODE REVIEW

**Comment by piotrvv** [comment]
`  ../../inetutils-2.5/libinetutils/daemon.c:125:3: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
    125 |   memset ((char *)&sa, 0, sizeof(sa));
        |   ^~~~~~
  ../../inetutils-2.5/libinetutils/daemon.c:58:1: note: include '<string.h>' or provide a declaration of 'memset'
     57 | #include <attribute.h>
    +++ |+#include <string.h>
     58 | 
  ../../inetutils-2.5/libinetutils/daemon.c:125:3: warning: incompatible implicit declaration of built-in function 'memset' [-Wbuiltin-declaration-mismatch]
    125 |   memset ((char *)&sa, 0, sizeof(sa));
        |   ^~~~~~
  ../../inetutils-2.5/libinetutils/daemon.c:125:3: note: include '<string.h>' or provide a declaration of 'memset'
`
From the logs above.

**Comment by lazka** [comment]
uh, thanks

**Comment by Biswa96** [comment]
Warnings should be fixed upstream if it does not cause any issue in the package.

**Comment by lazka** [comment]
In this case it comes from the cygwin patch we imported though :)

**Comment by piotrvv** [comment]
@Biswa96 Cocom package still not fixed.

**Comment by lazka** [comment]
Fixed in 7e750ecc1da0c610d2fe533e484b9b5df60c2cdb

@tyan0 fyi^ (we use a newer gcc, so maybe due to that)

**Pull request merged**
