### PR TITLE
sqlite 3.42.0: remove unnecessary dependencies from split packages

### PR DESCRIPTION
**Pull request by jannick0**
NB: The github action run on my fork hangs in step `dll check` for whatever reason. Let's see what happens here.

### CODE REVIEW

**Comment by jannick0** [comment]
@lazka Any idea why the job hangs at [`dll check`](https://github.com/msys2/MSYS2-packages/actions/runs/5092158884/jobs/9153140650?pr=3809#step:10:927)? Anything within the .ci process? ... just wondering.

**Comment by lazka** [comment]
hm, no idea

**Comment by jannick0** [comment]
I'll try to check with other packages with the same minor issue tomorrow. Let's see ...

**Comment by lazka** [comment]
I could be wrong, but I think `ldd` sometimes hangs with 100% CPU.

re the changes, lgtm. This makes us drop "tcl" from base, which is nice too :)

**Pull request merged**
