### PR TITLE
Add regional mirrors

### PR DESCRIPTION
**Pull request by danyeaw**
Adds 8 additional mirrors 🎉 .

A special thanks to:

- Gaphor Project for hosting one on DigitalOcean (USA)
- James Madison University (USA)
- University of Crete (Greece)
- Umeå University (Sweden)
- Piconets-Webwerks (India)
- Quantum Mirror (Hungry)
- Dotsrc.org (Denmark)
- Universidad de La Frontera (Chile)

I will also create another issue to discuss using [MirrorBits](https://github.com/etix/mirrorbits). I heard many times from the mirrors that this is a best practice.

Should we also create a webpage to capture everyone's names and contact info?

### CODE REVIEW

**Comment by Biswa96** [comment]
As mirrors are increased, I am thinking of adding the regions as comments like in ArchLinux mirrorlist. Also to maintainers, do we need some kind of written/signed permission (like CLA) from the mirror owners?

**Comment by danyeaw** [comment]
> As mirrors are increased, I am thinking of adding the regions as comments like in ArchLinux mirrorlist.

I think this is a good idea, it looks like they organized the mirrorlist by country. I can weave that in to this PR.

> Also to maintainers, do we need some kind of written/signed permission (like CLA) from the mirror owners?

I don't know what you mean by this, we have permission to use the mirrors. We can't abuse the mirrors of course, I think this is why MirrorBits would help distribute the load to prevent overuse of a single mirror.

**Comment by 1480c1** [comment]
btw, you might want to contact the people hosting the tuna mirror since they seem to have a random icons folder https://mirrors.tuna.tsinghua.edu.cn/msys2/icons/ which I am not sure if they meant to have that

**Comment by 1480c1** [comment]
btw, same for http://mirror.bit.edu.cn/msys2/icons/

**Comment by danyeaw** [comment]
I decided not to organize them by country. Arch is doing this because they are all commented out by default except for their mirror balancer server. As soon as we run rankmirrors they will no longer stay with their country group.

**Comment by 1480c1** [comment]
the one's I could rsync to are

```none
rsync://mirror.yandex.ru/mirrors/msys2/
rsync://mirrors.tuna.tsinghua.edu.cn/msys2/
rsync://mirror.selfnet.de/msys2/
rsync://ftp.acc.umu.se/mirror/msys2.org/
rsync://quantum-mirror.hu/msys2/
rsync://mirrors.dotsrc.org/msys2/

# rsync://mirror.bit.edu.cn/msys2/ # does not have msys2 in their rsync modules
# rsync://ftp.cc.uoc.gr/mirrors/msys2/ # does not have msys2 in their rsync modules
# rsync://mirror.ufro.cl/msys2/ # does not have msys2 in their rsync modules
# rsync://mirrors.sjtug.sjtu.edu.cn/msys2/ # only has qt
```

**Comment by danyeaw** [comment]
> Also, do we know how many of them support rsyncing?

The DigitalOcean one does not, most of the rest that I add all support it.

**Comment by lazka** [comment]
> Should we also create a webpage to capture everyone's names and contact info?

What about a markdown file in the pacman-mirrors package/directory?

**Comment by lazka** [comment]
> > Also, do we know how many of them support rsyncing?
> 
> The DigitalOcean one does not, most of the rest that I add all support it.

I think he meant them providing an rsync server, not they being able to sync from our rsync server.

**Comment by danyeaw** [comment]
> What about a markdown file in the pacman-mirrors package/directory?

I like that idea, I could create that as part of a separate PR.

**Comment by jkcgs** [comment]
> # rsync://mirror.ufro.cl/msys2/ # does not have msys2 in their rsync modules

Hi, I'm the maintainer for this mirror. I'll add msys2 to rsync now, forgot to do this.

**Comment by danyeaw** [comment]
> Hi, I'm the maintainer for this mirror. I'll add msys2 to rsync now, forgot to do this.
Thanks @jkcgs !

**Comment by lazka** [comment]
> I'll add msys2 to rsync now, forgot to do this.

works nicely, thanks!

**Pull request merged**
