### PR TITLE
update lcov to 1.16

### PR DESCRIPTION
**Pull request by GitMensch**

### CODE REVIEW

**Comment by GitMensch** [comment]
Question: Why was that moved out of the MinGW packages? Did it just not work "as expected"? If this is the case maybe it can be included again (the new version has some Win32 related bug fixes like crlf handling; if this isn't enough then the work on https://github.com/linux-test-project/lcov/pull/74/files seems to be enough to create a patch file (should be much smaller) for that).

Note: I recognized that the 001-mingw-lcov1.12-handle-equals-signs.patch effectively comes from Debian "support GCC8" patch and was then removed in Debian with the "support GCC9" patch, see https://deb.debian.org/debian/pool/main/l/lcov/lcov_1.15-1.debian.tar.xz - so: do we still need that?

**Comment by lazka** [comment]
> Question: Why was that moved out of the MinGW packages, where it [originally came from](https://github.com/msys2/MINGW-packages/blob/f295b9ea89be310598901cec4bc160a6977ceb37/mingw-w64-lcov/PKGBUILD)?

Because of #7065

Feel free to add a mingw one if you get it to work.

> Note: I recognized that the 001-mingw-lcov1.12-handle-equals-signs.patch effectively comes from Debian "support GCC8" patch and was then removed in Debian with the "support GCC9" patch, see https://deb.debian.org/debian/pool/main/l/lcov/lcov_1.15-1.debian.tar.xz - so: do we still need that?

That patch is still used in Debian. I don't know enough about it to judge if it should be dropped.

**Comment by GitMensch** [comment]
Rechecked: the new lcov seems to work for me when generated as MinGW package, at least the simple test also worked without perl-JSON and perl-PerlIO-gzip.

This is the new PKGBUILD for msys:

```
# Contributor: Jordi De Groof <jordi dot degroof at gmail dot com>
# Contributor: Andre Klitzing <aklitzing () gmail () com>
# Contributor: Simon Sobisch <simonsobisch () gnu () org>

_realname=lcov
pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}")
pkgver=1.16
pkgrel=1
pkgdesc="front-end for GCC's coverage testing tool gcov"
arch=('any')
url="https://github.com/linux-test-project/lcov"
license=('GPL')
depends=("${MINGW_PACKAGE_PREFIX}-perl")
source=("https://github.com/linux-test-project/lcov/releases/download/v${pkgver}/${_realname}-${pkgver}.tar.gz"
        "001-mingw-lcov1.12-handle-equals-signs.patch"
        "002-mingw-lcov1.12-fix-undef-behaviour.patch")
sha256sums=('987031ad5528c8a746d4b52b380bc1bffe412de1f2b9c2ba5224995668e3240b'
            '54728aa4e244d3662c65ba91fb486dc1d5c64d9d55745ee334c4131109dc233c'
            'ceaf41f7cc9cea5a6fc4b0385ffef10d1ab8812acd2a5b16dcd8d7bca7120488')

prepare() {
  cd "${srcdir}/${_realname}-${pkgver}"

  patch -p1 -i ${srcdir}/001-mingw-lcov1.12-handle-equals-signs.patch
  patch -p1 -i ${srcdir}/002-mingw-lcov1.12-fix-undef-behaviour.patch
}

package() {
  cd "${srcdir}/${_realname}-${pkgver}"

  make PREFIX="${MINGW_PREFIX}" DESTDIR="${pkgdir}" install
}
```

Is there anything missing? Otherwise I'll try to checkout the old version, then replacing with the current data, then push + PR.

**Comment by lazka** [comment]
I don't see you adjusting the perl shebang, so are you sure this is using mingw perl?

**Comment by GitMensch** [comment]
I'm not sure what you mean; it depends on `"${MINGW_PACKAGE_PREFIX}-perl"` and after installing the package (

```sh
me@pc MINGW64 ~
$ lcov --version
lcov: LCOV version 1.14
# now running pacman -U mingw-w64-x86_64-lcov-1.16-1-any.pkg.tar.zst in MSYS
me@pc MINGW64 ~
$ lcov --version
lcov: LCOV version 1.16
me@pc MINGW64 ~
$ which perl
/mingw64/bin/perl
```

So I _think_ that was installed correctly and uses the mingw perl (actually whatever perl is in path, but that should be the mingw one because of the dependency), no?

After installing it I've tested this in MINGW64 as follows:

```sh
gcov main.c foo.c
File 'main.c'
Lines executed:100.00% of 5
Creating 'main.c.gcov'

File 'D:/dev/msys64/mingw64/include/stdio.h'
Lines executed:100.00% of 5
Creating 'stdio.h.gcov'

File 'foo.c'
Lines executed:85.71% of 7
Creating 'foo.c.gcov'

Lines executed:94.12% of 17
lcov --capture --directory . --output-file coverage.info
Capturing coverage data from .
Found gcov version: 12.1.0
Using intermediate gcov format
Using JSON module JSON::PP
Scanning . for .gcda files ...
Found 2 data files in .
Processing foo.gcda
Processing main.gcda
Finished .info-file creation
genhtml coverage.info --output-directory out
Reading data file coverage.info
Found 3 entries.
Found common filename prefix "D:/dev/msys64/home/me/lcov"
Writing .css and .png files.
Generating output.
Processing file /d/dev/msys64/mingw64/include/stdio.h
Processing file gcov-example-master/foo.c
Processing file gcov-example-master/main.c
Writing directory view page.
Overall coverage rate:
  lines......: 94.1% (16 of 17 lines)
  functions..: 100.0% (3 of 3 functions)
```

then looking at

coverage-report

**Comment by GitMensch** [comment]
> I don't see you adjusting the perl shebang, so are you sure this is using mingw perl?

Got it, adjusted for https://github.com/msys2/MINGW-packages/pull/11805

**Comment by lazka** [comment]
> ```shell
> Processing file /d/dev/msys64/mingw64/include/stdio.h
> Processing file gcov-example-master/foo.c
> Processing file gcov-example-master/main.c
> ```

This looks like cygwin perl to me

**Comment by GitMensch** [comment]
The GCC8 patch is applied before the GCC9 one - which removes the ===== again.

**Pull request merged**
