### PR TITLE
Add sipp

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by lazka** [comment]
What do you need this for?

**Comment by orgads** [comment]
It's a useful tool for voip developers :)

I build it locally, but would prefer to have it as a package.

**Comment by sskras** [comment]
@orgads. Maybe doing MINGW package instead of MSYS2 package would be enough?

**Comment by orgads** [comment]
I wish, but MinGW is not supported.

**Comment by sskras** [comment]
Ummm, I thought it was fine: https://github.com/SIPp/sipp/issues/23#issuecomment-634078542

> sipp can be built using mingw without any cygwin/msys dependencies.

**Comment by orgads** [comment]
I wrote this? 😁

I just checked and it doesn't build. I'll try to look into it.

**Comment by sskras** [comment]
Maybe a regression was introduced in the meantime.

**Comment by orgads** [comment]
No, this was probably a mistake. I always used cygwin/msys for building it.

**Comment by orgads** [comment]
I tried porting the changes from polycom. There are a million conflicts, it's not worth the effort.

**Comment by sskras** [comment]
Ack. Sad to hear...

As a half off-topic, I tried building sipp on **Midipix** (the more effective Cygwin alternative).
It seems to lack recent gcc and thus a support of C++11 too:
```sh
midipix@DESKTOP-O7JE7JE /dev/mnt/d/_BACKUPS/src/github.com/SIPp/sipp
$ make
Scanning dependencies of target version
[  0%] Built target version
Scanning dependencies of target sipp
[  2%] Building CXX object CMakeFiles/sipp.dir/src/actions.cpp.o
cc1plus: error: unrecognized command line option '-std=c++11'
make[2]: *** [CMakeFiles/sipp.dir/build.make:63: CMakeFiles/sipp.dir/src/actions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/sipp.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

midipix@DESKTOP-O7JE7JE /dev/mnt/d/_BACKUPS/src/github.com/SIPp/sipp
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/bin/../libexec/gcc/x86_64-nt64-midipix/4.6.4/lto-wrapper
Target: x86_64-nt64-midipix
Configured with: ../cbb-gcc-4.6.4/configure --disable-sjlj-exceptions --host=x86_64-nt64-midipix --prefix=/ --with-elf=/home/saukrs/midipix/nt64/release/native --with-gmp=/home/saukrs/midipix/nt64/release/native --with-mpc=/home/saukrs/midipix/nt64/release/native --with-mpfr=/home/saukrs/midipix/nt64/release/native --with-sysroot= --disable-bootstrap --disable-libmudflap --disable-multilib --disable-nls --disable-obsolete --disable-symvers --enable-canonical-system-headers --enable-__cxa_atexit --enable-debug --enable-gnu-indirect-function --enable-gnu-unique-object --enable-initfini-array --enable-languages=c,c++,fortran,objc,lto --enable-libstdcxx-debug --enable-lto --enable-multiarch --enable-secureplt --enable-shared --enable-threads=posix --target=x86_64-nt64-midipix --with-fpmath=sse
Thread model: posix
gcc version 4.6.4 (GCC)

$ uname -a
midipix DESKTOP-O7JE7JE pre-alpha-internal-2bc731105275d52feb98f3b47cf454e7674ab739 2022.11.18.20.22.52 x86_64 Midipix
```

**Comment by orgads** [comment]
ping?

@lazka, if you don't approve, I'll close it. Just let me know.

**Comment by lazka** [comment]
We've talked about coming up with better rules for what goes into this repo in the last week. Let's leave this open for now.

**Comment by orgads** [comment]
ping?

**Pull request closed without merging**
