### PR TITLE
python: Update to 3.9.5

### PR DESCRIPTION
**Pull request by lazka**
All the dropped changes seem no longer be needed (static is off by default,
the cygwin patch for .exe is upstream)

### CODE REVIEW

**Comment by Biswa96** [comment]
Those Win7 support concerns?

**Comment by lazka** [comment]
This is cygwin, so shouldn't matter, no?

**Comment by naveen521kk** [comment]
Maybe I will try them :)

**Comment by naveen521kk** [comment]
Got this 
<details><summary>Error</summary>
```py
$ ./python -v -v
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__init__.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/__init__.cpython-39.pyc'
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/codecs.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/codecs.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/codecs.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/codecs.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/codecs.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/codecs.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/codecs.cpython-39.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff73d00>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/aliases.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/aliases.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/aliases.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/aliases.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/aliases.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/aliases.cpython-39.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff1f2b0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff73af0>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/utf_8.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/utf_8.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/utf_8.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/utf_8.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/utf_8.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/utf_8.cpython-39.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff739d0>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/latin_1.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/latin_1.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/latin_1.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/latin_1.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/latin_1.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/encodings/__pycache__/latin_1.cpython-39.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff1f3d0>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/io.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/io.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/io.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/io.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/io.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/io.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/io.cpython-39.pyc'
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/abc.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/abc.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/abc.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/abc.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/abc.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/abc.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/abc.cpython-39.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff1f880>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff1f5b0>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/site.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/site.cpython-39.pyc'
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/os.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/os.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/os.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/os.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/os.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/os.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/os.cpython-39.pyc'
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/stat.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/stat.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/stat.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/stat.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/stat.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/stat.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/stat.cpython-39.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x6ffffed2130>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_collections_abc.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_collections_abc.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_collections_abc.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_collections_abc.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_collections_abc.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/_collections_abc.cpython-39.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x6ffffed21c0>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/posixpath.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/posixpath.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/posixpath.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/posixpath.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/posixpath.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/posixpath.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/posixpath.cpython-39.pyc'
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/genericpath.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/genericpath.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/genericpath.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/genericpath.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/genericpath.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/genericpath.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/genericpath.cpython-39.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x6ffffef77f0>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x6ffffed2af0>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff36820>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_sitebuiltins.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_sitebuiltins.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_sitebuiltins.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_sitebuiltins.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/_sitebuiltins.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/_sitebuiltins.cpython-39.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x6ffffec8d30>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/sitecustomize.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/sitecustomize.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/sitecustomize.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/sitecustomize.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/sitecustomize.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/sitecustomize.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/sitecustomize.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/sitecustomize.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/sitecustomize.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/sitecustomize.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/sitecustomize.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/sitecustomize.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/sitecustomize.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/sitecustomize.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/sitecustomize.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/usercustomize.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/usercustomize.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/usercustomize.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/usercustomize.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/usercustomize.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/usercustomize.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/usercustomize.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/usercustomize.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/usercustomize.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/usercustomize.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/usercustomize.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/usercustomize.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/usercustomize.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/usercustomize.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/site-packages/usercustomize.pyc
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x6fffff1f8b0>
Python 3.9.5 (default, May 15 2021, 13:06:36)
[GCC 10.2.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/readline.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/readline.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/readline.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/readline.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/readline.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/readline.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/readline.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/readline.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/readline.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/readline.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/readline.cpython-39-x86_64-msys.dll
# extension module 'readline' loaded from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/readline.cpython-39-x86_64-msys.dll'
# extension module 'readline' executed from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/lib-dynload/readline.cpython-39-x86_64-msys.dll'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object at 0x6ffffef7df0>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/rlcompleter.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/rlcompleter.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/rlcompleter.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/rlcompleter.py
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/bin/rlcompleter.pyc
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/rlcompleter.cpython-39-x86_64-msys.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/rlcompleter.abi3.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/rlcompleter.dll
# trying /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/rlcompleter.py
# /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/rlcompleter.cpython-39.pyc matches /h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/rlcompleter.py
# code object from '/h/mingw/msys2-py/python-3.9.5-1-x86_64.pkg/usr/lib/python3.9/__pycache__/rlcompleter.cpython-39.pyc'
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object at 0x6ffffef7fd0>
>>>
```
</details>

**Comment by lazka** [comment]
tested various things, everything looks good. ship it! (to staging)

**Pull request merged**
