### PR TITLE
python: switch default mp start method to "spawn" and disable "forkserver"

### PR DESCRIPTION
**Pull request by lazka**
"forkserver" doesn't work, and "fork" is deprecated, so give "spawn" a try See https://github.com/msys2/MSYS2-packages/pull/4743#issuecomment-2213043559

### CODE REVIEW

**Comment by lazka** [comment]
See https://www.msys2.org/news/#2024-07-08-file-conflicts-when-updating-python

**Comment by piotrvv** [comment]
May I know why make it so difficult to build python?

**Comment by lazka** [comment]
What do you mean?

**Comment by piotrvv** [comment]
I'm asking this because msys-*.dll files are larger in the sources like in the pacman package.

**Comment by jeremyd2019** [comment]
> May I know why make it so difficult to build python?

I think both cygwin and mingw are unsupported targets upstream, so we have to figure out how to patch things ourselves.  Also, it seems like many times we are ahead of cygwin's versions of packages, so we are generally on the leading edge of figuring this stuff out (I think cygwin is still on python 3.9).

**Pull request merged**
