### PR TITLE
mingw-w64-cross-compiler-rt and -clang i686

### PR DESCRIPTION
**Pull request by jeremyd2019**
Simple loop to build both x86_64 and i686 target libraries, as is done in -crt.  I have not actually looked at the resulting binaries.

### CODE REVIEW

**Comment by mati865** [comment]
The problem with i686 is we cannot use 32bit LLD to link big packages (like LLVM) : https://bugs.llvm.org/show_bug.cgi?id=42388#c6

**Comment by jeremyd2019** [comment]
> The problem with i686 is we cannot use 32bit LLD to link big packages (like LLVM)

☹️ 

Does this PR look OK though?

**Comment by mati865** [comment]
Yeah, PR itself looks fine.

**Comment by jeremyd2019** [comment]
I built this locally on my i686 machine last night, and built a quick test c++ program with it just now that succeeded and ran properly.

**Comment by lazka** [comment]
It doesn't complicate things too much so seems fine I guess, even if it doesn't work in the long run.

@mati865 ok to merge?

**Review by mati865 — APPROVED** [review]

**Comment by jeremyd2019** [comment]
I was thinking/hoping that this should make adding arm/aarch64 pretty straightforward too.  Though I don't have any such hardware to try it myself.

**Comment by mati865** [comment]
Does Cygwin work on ARM/Aarch64?

**Comment by jeremyd2019** [comment]
My understanding is that it at least runs under emulation.  So it seems to me it could be used to bootstrap a native toolchain.  Theoretically.  Something interesting for those with the interest and hardware to try, anyway.  I think I remember @Biswa96 talking about this at one point.

**Comment by mati865** [comment]
I think Cygwin taps too deeply into the system for emulation to work reliably.
Cross compilation will be possible though.

**Pull request merged**
