### PR TITLE
libbobcat: add makedepends on git

### PR DESCRIPTION
**Pull request by mmuetzel**

### CODE REVIEW

**Comment by mmuetzel** [comment]
Oops. Forgot to bump pkgrel.

Is that needed if it didn't build previously?

**Comment by lazka** [comment]
> Oops. Forgot to bump pkgrel.
> 
> Is that needed if it didn't build previously?

Yes. I can rebuild via autobuildcontroller either way though.

**Comment by lazka** [comment]
(I also had other errors with libbobcat locally, let's see)

**Comment by mmuetzel** [comment]
> Yes. I can rebuild via autobuildcontroller either way though.

I'll let the CI finish and bump if it succeeds.

> (you can get access too if you want)

That might be useful. How does that work?

**Comment by lazka** [comment]
> > Yes. I can rebuild via autobuildcontroller either way though.
> 
> I'll let the CI finish and bump if it succeeds.
> 
> > (you can get access too if you want)
> 
> That might be useful. How does that work?

Go to https://packages.msys2.org/queue, click the link in "Maintainers can control the build pipeline [here](https://autobuildcontroller.msys2.org/).", log in via github

**Pull request merged**
