### PR TITLE
pacman: update to 6.0.0

### PR DESCRIPTION
**Pull request by lazka**
ParallelDownloads seem broken (they download sequentially here and the later ones hit the timeout limit). Maybe it's sourceforge, but if all fails we can disable it by default.

### CODE REVIEW

**Comment by lazka** [comment]
It's sourceforge blocking multiple connections, so we need to default to non-parallel downloads (it doesn't add much anyway..)

**Comment by lazka** [comment]
rebased on master, disabled parallel downloads per default because of sourceforge

**Comment by naveen521kk** [comment]
sourceforge?  is it a thing to worry about now?

**Comment by lazka** [comment]
no

**Comment by lazka** [comment]
6.0 is out. I'll try to rebase this in the coming days.

One regression came up on the pacman IRC re corrupt downloads on broken mirrors, so we should wait for a fix before replacing 5.x.

**Comment by lazka** [comment]
> One regression came up on the pacman IRC re corrupt downloads on broken mirrors, so we should wait for a fix before replacing 5.x.

pacman got released without this so I guess not that important

**Pull request merged**
