### PR TITLE
libqrencode: update to 4.0.2

### PR DESCRIPTION
**Pull request by taozuhong**
libqrencode: update to 4.0.2

### CODE REVIEW

**Comment by taozuhong** [comment]
@Alexpux 
the script break down at the source path, could you give me hand to solve this problem?

**Comment by Biswa96** [comment]
Please first build the package in your machine and check if it builds. CI isn't a debugging tool. The link should have `v${pkgver}`. Also you may have to add `replaces` and `conflicts` entries as you've replaced got version with a released one. Is it possible to convert this library to mingw-w64 (native) one?

**Comment by taozuhong** [comment]
@Biswa96 you are right exactly.

the PKGBUILD script can debug on local machine, not yet known it.

**Comment by lazka** [comment]
`pass` needs a pkgrel bump as well since this changed the DLL version and `pass` needs a rebuild.

**Comment by taozuhong** [comment]
@lazka you mean that set pkgrel=2, am I right?  it is done.

**Comment by Alexpux** [comment]
@taozuhong you must add to PKGBUILD provides, replaces and conflicts entries. And set pkgrel to 1

**Pull request merged**
