### PR TITLE
tcl: split development files to separate package

### PR DESCRIPTION
**Pull request by Biswa96**
This is to remove any potential conflict with mingw tcl package

### CODE REVIEW

**Comment by Biswa96** [comment]
Should dependent packages be rebuilt with new tcl-devel makedepends?

**Comment by lazka** [comment]
> Should dependent packages be rebuilt with new tcl-devel makedepends?

expect and sqlite link against it, so they need "tcl-devel" in makedepends and a rebuild for good measure.

btw `/usr/share/man/man3/Tcl_*` also seems development related, but we could also add a tcl-doc in the future like debian does: https://packages.debian.org/sid/all/tcl8.6-doc/filelist Feel free to ignore though.

**Comment by Biswa96** [comment]
> we could also add a tcl-doc in the future like debian does

I have added the tcl-doc package with all man3 files.

Another problem arises. expect can not be rebuilt, even with existing tcl package.

```
checking for Tcl public headers... /usr/include
checking for Tcl private include files... configure: error: Cannot find private header tclInt.h in /usr/include
```

**Comment by lazka** [comment]
I'll have a look

**Comment by Biswa96** [comment]
Thanks, now sqlite and expect are built without any issue.

**Pull request merged**
