### PR TITLE
pacman: Add Japanese translation

### PR DESCRIPTION
**Pull request by k-takata**
Add the Japanese translation back which was removed in #4591.

### CODE REVIEW

**Comment by k-takata** [comment]
Should I add this patch to the msys2/msys2-packman repository?

**Comment by Biswa96** [comment]
It should be added to upstream https://gitlab.archlinux.org/pacman/pacman

**Comment by k-takata** [comment]
No, these messages are MSYS2 specific messages and they are not included in the upstream source code.
This is the commit: https://github.com/msys2/msys2-pacman/commit/9d91ab906d427f87c5115211b11f0ebef364515c

See also the previous discussion: https://github.com/msys2/MSYS2-packages/pull/1786

**Comment by Biswa96** [comment]
So, the patches should be msys2 pacman.

**Comment by k-takata** [comment]
Created a PR there: https://github.com/msys2/msys2-pacman/pull/53

**Comment by lazka** [comment]
Fixed via #4905

**Pull request closed without merging**
