### PR TITLE
Remove python2, python2-pip and python2-setuptools

### PR DESCRIPTION
**Pull request by lazka**
Nothing in the repo depends on them anymore, not sure if there are any external users though.

### CODE REVIEW

**Comment by mingwandroid** [comment]
Bye bye python 2! It was nice knowing you.

**Comment by ofry** [comment]
Vera++ depends on Python 2.7...

**Comment by ofry** [comment]
MinGW version Python 2 still will exist, right?

**Comment by lazka** [comment]
> MinGW version Python 2 still will exist, right?

yes

**Pull request merged**
