### PR TITLE
Add Clarkson University Mirror and Document Others

### PR DESCRIPTION
**Pull request by danyeaw**
This PR adds Clarkson University as a mirror and documents the others using a markdown file:

- Location
- Hosting Organization
- URLs
- Contact

Thanks to Clarkson University for hosting us :tada:

### CODE REVIEW

**Comment by 1480c1** [comment]
Would it be better to use the mailto with the actual email, or use a `First Name <email at mymail.org>` format to prevent scraping of emails for personal emails?

Also, I recommend boxing URLs with either `<>` like `<https://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/>` or using backticks so it shows up as `<code>` like `https://www2.futureware.at/~nickoe/msys2-mirror/mingw/x86_64/`, especially for the rsync URLs so it doesn't look too weird next to the http(s) urls

**Comment by danyeaw** [comment]
@1480c1 Thanks for the feedback on the markdown url formats, I have updated the PR.

I'm not sure why the CI is downgrading packages and then failing.

**Comment by jeremyd2019** [comment]
> I'm not sure why the CI is downgrading packages and then failing.

msys2/MINGW-packages#7117

**Comment by cbrt64** [comment]
s/Hungry/Hungary/

**Comment by danyeaw** [comment]
@cbrt64 Thanks, fixed my typo.

**Comment by lazka** [comment]
Thanks!

**Pull request merged**
