### PR TITLE
jsoncpp: Update to 1.9.4

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by ihnorton** [comment]
This update appears to break the CMake package due to a change in the libjsoncpp name (the name generation scheme [has issue](https://github.com/open-source-parsers/jsoncpp/issues/1170)). We got the following on our CI after this update propagated:

```
D:/a/_temp/msys/msys64/mingw64/bin/cmake.exe: error while loading shared libraries: libjsoncpp-22.dll: cannot open shared object file: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...
Error: Process completed with exit code 1.
```

Can this be reverted, or a rebuild triggered for CMake?

**Comment by lazka** [comment]
Created https://github.com/msys2/MSYS2-packages/commit/37dddb88471d9013d6887921ccbc68de79c487e7 and https://github.com/msys2/MINGW-packages/pull/7076

@podsvirov please include required rebuilds in your PRs in the future (I hope we can automate this maybe...)

**Comment by ihnorton** [comment]
Looking at [the diff from 1.9.3..1.9.4](https://github.com/open-source-parsers/jsoncpp/compare/1.9.3...1.9.4#diff-af3b638bc2a3e6c650974192a53c7291) I'm a bit confused how this happened, because the SOVERSION was set to 24 in 1.9.3. However, the [cmake package](https://packages.msys2.org/package/mingw-w64-x86_64-cmake) from here very clearly links `-22`:

```
objdump -x cmake.exe
...
 007a712c       007a8370 00000000 00000000 007af634 007a9940

        DLL Name: libjsoncpp-22.dll
        vma:  Hint/Ord Member-Name Bound-To
```

Anyway, thanks for the rebuild!

**Comment by lazka** [comment]
You are using the mingw build, 1.9.3 was skipped: https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-jsoncpp

**Comment by podsvirov** [comment]
> Created https://github.com/msys2/MSYS2-packages/commit/37dddb88471d9013d6887921ccbc68de79c487e7 and https://github.com/msys2/MINGW-packages/pull/7076
> 
> @podsvirov please include required rebuilds in your PRs in the future (I hope we can automate this maybe...)

@lazka , I apologize and thank you, I will try :-)

**Comment by lazka** [comment]
fixed now, sorry for the inconvenience

**Pull request merged**
