### PR TITLE
perl-HTTP-Daemon: update to 6.06

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Alexpux** [comment]
@Biswa96 you need add new dependencies needed for HTTP-Daemon

**Comment by lazka** [comment]
@Alexpux which one do you mean? `perl-module-build-tiny` which was added in Arch?

**Comment by Biswa96** [comment]
`perl-ExtUtils-Helpers` package may need some patching. May you add that dependency?

**Comment by Biswa96** [comment]
`perl-module-build-tiny` needs `perl-ExtUtils-Helpers` package which may need some patching. May you add that dependency?

**Comment by Biswa96** [comment]
The dependencies of `perl-module-build-tiny` may need some patching because the source files only has `cygwin` mentioned, not msys. May you add that dependency?

**Comment by hiroakit** [comment]
Ref #1914

**Comment by Alexpux** [comment]
> 
> 
> The dependencies of `perl-module-build-tiny` may need some patching because the source files only has `cygwin` mentioned, not msys. May you add that dependency?

This need add bunch of new packages. I dont have time for it now

**Pull request closed without merging**
