### PR TITLE
brotli: drop python2-brotli

### PR DESCRIPTION
**Pull request by lazka**
Nothing depends on it and there is python-brotli for Python 3.

@OTLabs any objections?

### CODE REVIEW

**Comment by OTLabs** [comment]
@lazka Agree!

**Comment by lazka** [comment]
The i686 build hangs in CI :/ no idea

**Comment by OTLabs** [comment]
`/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_suite'`

**Comment by lazka** [comment]
Adding a rebaseall run in CI makes things work again, not sure if this is the right fix though.

**Pull request merged**
