### PR TITLE
fortune-mod

### PR DESCRIPTION
**Pull request by 5paceToast**
New package: fortune mod (9708 edition).

### CODE REVIEW

**Comment by 5paceToast** [comment]
New package: PyCrypto for python2.

**Comment by elieux** [comment]
@5paceToast, without wanting to sound rude, I have to ask -- how should these packages benefit MSYS2?

**Comment by 5paceToast** [comment]
Msys2 is a Cygwin fork.
The project's [summary](http://sourceforge.net/projects/msys2/) states `We wanted a package management system to provide easy installation of packages` and that it features `Hundreds of FOSS packages`.
The general idea behind wanting a package management system to provide easy installation of packages is that you want to have various useful packages to install.
Both of these (and any subsequent ones) are widely used in other distributions.
While the project also states that the main goal is facilitating the use of autotools and similar tools for building native applications, I was under the impression that it is also interested in improving on cygwin.
If that's not the case (aka I'm told so by a project member, or the PR is refused) I'll simply run my own package host (or keep them for personal use).

**Comment by oysteinkrog** [comment]
Yay fortune:)
You should probably split this though, one PR for each new package.

**Comment by mingwandroid** [comment]
I *think* @elieux's question was why this wasn't submitted as a MinGW-w64 package to https://github.com/Alexpux/MINGW-packages instead though it could just be that he considers this a jokey package, I'm not sure!

**Comment by mingwandroid** [comment]
.. Also:
```
# Maintainer: Orphaned
# I'm not planning to maintain this, but I am planning to include a git version.
```
doesn't give us good vibes either. For fortune-mod, that may be irrelevant but for PyCrypto accepting maintenance responsibilities (of the non-git version) would be expected, since otherwise someone else will have to.

**Comment by mingwandroid** [comment]
Finally, maintenance of 'release' packages is much more important to us that maintenance of '-git' packages since we don't packages the '-git' ones; they're only there for developers as and when they want to build that software for development purposes.

**Comment by 5paceToast** [comment]
In terms of PyCrypto, some potential uses require it (anything that uses Crypto with Python, for example).
While my schedule/free-time count varies wildly to the point that I cannot make any promises in terms of maintenance, having a version of it (even if somewhat outdated) is still beneficial.

I'll split the two PRs sometime this week and make two of them (and link them here).

**Comment by magneticflux-** [comment]
@5paceToast Wanna make/link those PRs here? I know `fortune` isn't exactly crucial to have, but it's a nicety, and PyCrypto might actually be useful to have.

**Comment by lazka** [comment]
Feel free to open a new PR with a proper reason for why you need it.

Since there hasn't been any update in years, closing.

**Pull request closed without merging**
